* The New Human Agenda
在人类的新世纪中，人类已经告别了影响自己很久的贫困，健康和战争问题;
即将使用更先进的科学手段来达到长生不老，永恒的幸福和升级为神人的能力。

** old
*** 繁荣 The Biological Poverty Line
**** 以往
大多数人类生活在贫困线附近。一个小的疏忽或一点厄运都会对整个家庭和村庄宣告死亡。
在社会层面上不幸和愚昧造成了大量的饥荒。

**** 现状
在过去的一百年见，技术、经济和政治的发展在人类和生物学的平均线之间创造了越来越牢固的安全网。

现代的个人保险机制、政府机构和国际NGO虽然不会使危险人群免于贫困，
但会使他们不会死于饥饿。

即使在战争或自然灾害发生时，国际援助的介入也能狗成功防止饥荒。

在社会层面上全球贸易网络使干旱和食品成为了商业机会，并且使克服食品短缺更快更便宜。

当前在大多数国家，过度饮食成为了比贫困更严重的问题。在
2010年饥荒和营养不良一共杀死了一百万人，与此同时肥胖杀死了三百万人。

*** 健康 Invisible Armadas(plagues, infectious diseases)
**** 以往
从公元1330年开始在20年内席卷亚洲欧洲和北非的黑死病总共杀死了七千五百万到2亿人。

儿童因为缺乏免疫力，所以死亡率一直很高，大约三分之一的儿童会由于营养不良和疾病在成年之前死去。

**** 现状
二十世纪的医学取得了前所未有的成就，提供了疫苗、抗生素、加强的保健和更好的医疗设施。

儿童死亡率达到历史的最低点，仅为百分之五。

2002年SARS曾经引发了新世纪黑死病的恐惧，但是最终在全世界只造成了1000人的死亡。

*** 和谐 Breaking the Law of the Jungle
在历史上，人类社会中和平是暂时的，而战争才是常态。

从20世纪后半页开始，在大多数地区战争越来越罕见。

**** 以往
在古农业社会百分之15的人类死于暴力，而在21世纪这个比例减少到了百分之1。

**** 现状
在2012年大约有五千六百万人去世，其中62万人死于暴力。相反有80万人死于自杀，
一百五十万人死于糖尿病。

核武器造成的恐怖平衡使得大国之间的战争更像是集体自杀。
同时全球经济也由资源型经济转变为知识型经济，使得战争带来的经济利益急剧下降。
战争也渐渐的局限在落后的资源型经济体之间。

恐怖主义就像瓷器店里的苍蝇（牛）--依靠制造混乱来造成破坏。

** new
*** 长生不老 immortality
**** 以往
宗教认为人生存的意义在于死后的生活，因此死亡是世界上一个重要的并且积极的部分。

**** 现状
对于现代人来说，死亡更像是一个可以并且应当解决的技术问题。

在20世纪以来，虽然人们的生命周期已经从40岁延长到70岁，
但这些都只是让人们避免过早死于饥饿疾病等因素，科学的发展还尚未能延长人类的自然生命周期。

**** 未来
科技的发展是很难预料的，也许不久的将来这些都不再是难题;
但永生的出现可能也会对人类的文化价值观带来强烈的颠覆。

*** 幸福 happiness
**** 以往
在历史上非常多的思想家，预言家和普通人都认为幸福而不是生命本身才是至善的。

对毕达哥拉斯来说幸福是个人的追求，但对现代的思想家来说，却是一个集体的事业。

值得注意的是美国的独立宣言中保障的是追求幸福的权利而不是快乐的权利本身。

**** 现在
追求幸福的权利，起初是来设想作为政府的限制，却在潜移默化中变成了幸福的权利，
就像人生来就有幸福的权利，我们的任何不满意都是有违人的基本权利，
因此政府被认为应该有所作为。

**** 问题
当毕达哥拉斯定义幸福作为至善时，他警告自己的追随者幸福是一项艰难的工作。
单独的物质成就并不会使我们满足太久。快乐的感觉很快就会转变成不快乐的。

**** 科学认识
在心理学的层面，幸福取决于我们的预期而不是客观的情况。

在生物学的层面，我们的期望和幸福都是由我们体内的生物化学反应所决定。

根据演化学的观点：人类的演化决定了无法享受恒定的快乐，人对幸福的追求只会越来越贪婪。

**** 未来展望
+ 生物化学的解决方法：研发提供人类无止境的快乐情绪的药物或治疗。
+ 佛教的建议：减少对快乐的追求，并且不让他们控制我们的生活。
+ 改造人类的身体和思维来享受永恒的快乐。

*** 神性 divinity
除了为了获得神圣的能力之外，为了克服衰老和不幸福，人类也会去掌握对自己生物基质进行神一般控制的能力。

人类从人升级为神可能会遵循三条路径：
+ 生物工程改造 biological engineering
+ 机械电子工程改造 cyborg engineering
+ 非有机体生物的改造 the engineering of non-organic beings

*** 学习历史的目的
学习历史的目的是为了让我们知道我们通常并没有考虑的可能性。

我们的世界是被一系列偶然的世界所创造，并且历史并不仅仅是被我们的科技、政治和社会所影响，
还有我们的思想、恐惧和梦想。

改变世界的运动通常始于重写历史（新的历史将会向我们解释当前的状况既不是自然的也不是永恒的。仅仅是一系列偶然的事件才造成了今天这个不公的现实），
之后让人们再次想象到未来的别的可能性。

* PART1 Homo Sapiens Conquers the World
** The Anthropocene
在人类的历史上，人类只要认为自己的能力比别的东西大，就不会再关注它们的“声音”。

*** 农业革命前
狩猎者/采集者没有把自己视为超级物种，因为他们很少意识到自己对生态系统的影响。

在他们的泛神论的世界观中，万物都在世界上有着自己的角色。

*** 农业革命后
而农民却生活在被自己的梦想和思维所控制和改造的社会。
因此在农业革命中，人类静默了动物和植物，使泛神论的巨大歌剧变成了人和上帝的对白。

在农民们的有神论的世界观中，上帝被赋予了两个角色：
+ 他们解释了为什么人类是如此特殊并且为什么人类应该主宰并剥削其他生物。
+ 上帝需要在人类和生态系统中调停。

*** 科技革命后
现代科技赋予人的力量超过了古代的上帝所给的，
因此在科技革命中，人类使上帝也保持静默，并孕育了新的宗教-人文主义。

人文主义的基础思想比如自由主义，共产主义和纳粹都来自人类有着宇宙中产生一切意义和权利的独一无二的本质。
宇宙中所发生的一切都根据对人类的影响来判断好坏。

*** 未来
当计算机程序拥有了超越人类的智力和空前的权利之后，我们是否应该认为程序的价值比人类的更大？
然后让程序就像我们对待动物那样对待我们？如果不允许，那我们人类除了更高的智力和权利之外，
又有什么其他的道德基础来剥削动物？

** The Human Spark
让人类如此特殊的既不是不存在的灵魂也不是无作用的意识，而是人类大规模合作的能力。

*** 灵魂并不存在
根据进化论，所有的生物学的实体从大象到DNA分子都是由可以被不断的组合和分解的更小的部分组成的。
那些无法被分解和改变的也无法通过自然选择而存在。所以人类的灵魂并不存在。

*** 意识是个副产品
意识是源源不断的主观感受，比如痛苦，快乐，愤怒和爱。
每个主观的经验都有两个基本的特征：感觉和欲望。
而且现代的政治和伦理学的大厦大多都建立在我们的主观体验之上。

一些科学家承认意识是真实的并且有着巨大的道德和政治价值，但是并不满足任何生物学方程。
而且我们越好地构建大脑的生存，我们就越难以解释意识的作用。
因此意识是特定大脑活动的无用的生物副产品。
就像喷气发动机轰鸣的噪音很大，但噪音却并不能推动飞船前进。

对于人类来说，我们今天能够区分有意识的心灵经验和无意识的大脑活动。
虽然我们远还未能够理解意识，科学家已经成功地识别了其中的一些电化学信号。

*** 大规模合作的能力让人类如此特别
事实上，我们统治全球的关键因素是我们能够团结大量人的能力。
而只有人类能够以一种灵活的方式和大量陌生人合作。

除了主观世界和客观世界之外，人们还创造了主体间的世界，在那里事物存在于人们的沟通之中。
在这里所有大规模的人类合作都基于对想象秩序的信念，这些信念被认为是无法避免的自然规律或者上帝的旨意，而不是人类的念头。

* PARTII Homo Sapiens Gives Meaning to the World
** The Storytellers
人类通过将现实和虚构相结合，增强了社会组织的能力。

*** 书写的作用
与此同时，因为书写使人类更习惯于通过复杂的符号体验到现实，
所以它使人类更加容易相信想象实体的存在。

书写确实能使官员管理国家变得更加高效了。

虽然将有时书写的幻想强加到现实中会产生巨大的灾难，
但相同的能力却也能使政党描绘了成功的美好图景，并且稳固了自己的权力。

书写的语言也许被认为是一个合适的描述现实的方式，
但是却也逐渐变成了重塑现实的有力的方式。

*** 现实和虚构
对于事实和虚构，如果你扭曲太多的事实，它会削弱你的影响力。
在另一方面，如果你不依赖一些幻想的故事，你就无法有效组织人类的大规模合作。

该如何辨别实体和虚构的实体--它能承受痛苦吗？

但是故事只是手段，它们不应该成为我们的目标或者教条。
当我们忘记了它们只是虚构的时候，我们就和现实脱轨了。

** The Odd Couple
宗教和科学确实在事实论断上存在冲突，但在人类发展上确是相互合作的，
科学提供力量，宗教提供组织秩序。

*** 什么是宗教
处于宗教中的人总认为外人看来超自然的事物也是自然的，比如
现代的物理学家认为是看不见的细菌造成的疾病，
而伏都教的牧师认为是看不见的恶魔造成的。
他们一样相信恶魔不是超自然的，
而是和细菌一样是自然的一部分。

宗教反应了在人类社会的框架上拥有超人的正当性。
它通过论证说自己反应了超人的法则来使人类的规则和价值拥有正当性。

宗教断言人类必须遵从一套不是由人发明的，人类也无法改变的自然法则。

宗教是一个保存社会秩序和组织大规模合作的工具。

*** 科学与宗教的冲突
宗教无法提供给我们任何实际的指导，
除非它做出了一些事实上的论断，
并且在此它会和科学冲突。

1.道德论断，比如人类的生命是宝贵的。
2.事实命题，比如人类的生命始于受精卵
3.道德论断和事实命题的合并，造成了实际的指导，比如
在受精后，你就不应该堕胎

宗教有着将事实命题转变为伦理判断的讨厌的趋势，
导致事实命题的背后经常隐藏着道德判断。

*** 科学与宗教的合作
科学总是需要宗教的协助来创造可行的人类设施。
科学研究世界如何运行，但却没有科学方法来决定人类应该行动。

宗教关注的是秩序，它的目的在于创造和维持社会秩序。
科学关注的是力量，它的目的在于获得治愈疾病，赢得战争和制造食物。

现代的历史可以看作科学和人文主义之间达成契约的过程。

** The Modern Covenant
人类在现代化的过程中获得了科学力量的同时也被迫了解了宇宙的无意义。
在现代化中，人类建立了对经济增长的信念的良性循环之中，也进入了不能停止的经济发展的巨轮。

*** 现代契约
现代性是一个合约：
人类同意放弃意义来交换权力。

从科学的理解来看，宇宙是一个盲目和无意义的过程，
充满了喧哗与骚动，却毫无意义。

*** 经济增长的必要性
现代性是建立在人们对经济增长的必要性的信念上的。

现代政治家和经济学家都坚持经济增长是必要的，因为：
1.当我们生产更多的时候，我们也可以消费更多，也就可以提高我们的生活水平了。
2.当人类的数量在极具增长的时候，经济增长能保证我们的生活水平不倒退。
3.经济增长能解决很多社会问题。

为了确保不断的增长，我们必须不断的发现新的资源。
一种方法是开发和征服新的土地。
科学对人类无知的发现提供了一个新的选择：不断发现新的知识。

百万年来，社会不断削减个人的欲望来将他们带入某种平衡。
人类的本性是贪婪的，但是社会的经济总量是固定的，
社会的和谐就取决于限制。
现代化改变了游戏规则，它激励人类去需求更多。

** The Humanist Revolution
根据人文注意的观点，人类必须从自己的内心体验找出意义，而且不仅是自己的意义，更是宇宙的意义。

现代性推动的主要宗教革命并不是对神失去了信心，而是对人类有了信心。

在伦理上，人文主义的座右铭是“感觉对了，就做吧”。
在政治上，人文主义告诉我们“选民能做出最好的选择”。
在美学上，人文主义说“看的人觉得美，就是美”。

在中世纪的欧洲，获得知识的主要公式是：知识=经文x逻辑。
科学革命的公式是：知识=实证数据x数学, 这个公式让我们在各个学科取得突破，但它有一个重大缺陷：无法处理价值和意义的问题。

人文主义提供了一个获取伦理只是的新公式：知识=体验x敏感性。
敏感性包括两个方面：第一，注意自己的知觉，情绪和想法；第二，允许这些知觉、情绪和想法影响自己。

人文主义的三大分支：
+ 正统派（自由主义）：每个人都是独特的，拥有独一无二的内在声音、永不重复的一连串体验。
+ 社会主义：要注意他人的感受，主义自己的行动如何影响他人的体验，并主张建立强有力的集体制度为我们解读这个世界。
+ 进化人文主义：源于达尔文的进化论，认为冲突是福不是祸，能够促成自然选择、推动进步。

宗教和科技总是跳着一支优雅微妙的探戈。双方互相推动、互相依赖，不能与对方离得太远。
科技之所以有求于宗教，是因为每种发明有许多可能的应用方式，而工程师就需要一些先知做出关键的决定，指出需要的方向。

传统宗教因为对现代技术不了解，从而无法对现代生活提出见解，也无法替代自由主义。
* PARTIII Homo Sapiens Loses Control
** The Time Bomb in the Laboratory
自由主义的基础有他深信不移的事实声明，而这些事实声明是过不了科学审查这一关。

自由主义重视个人自由，是因为相信人类有自由意志。
但从最新的科学来看，人的选择不是生物预设就是随机。

人体内至少有两种自我：
+ 体验自我
+ 叙事自我:通常用事件的高潮和最后结果来编织故事

体验自我和叙事自我并非各自独立，而是紧密交织的。
叙事自我也用到我们的种种体验，作为重要的故事素材。
反过来，这些故事也会塑造体验自我的种种感受。

每个人都有一个复杂的系统，会丢下我们大部分的体验，
只挑选留下几样，再与我们看过的电影、读过的小说、听过的演讲、做过的白日梦混合在一起，
编织出一个看似连贯的故事，告诉我们自己是谁，来自哪里、要去哪里。
** The Great Decoupling
人类的三项务实发展：
+ 人类将会失去在经济和军事上的用途，因此经济和政治制度将不再继续认同人类有太多价值。
+ 社会系统仍会认为人类整体有其价值，但个人无价值。
+ 社会系统仍会认为某些独特的个人有其价值，但这些人会是一些超人类的精英价值，而不是一般大众。

自由主义之所以成为意识形态的主流，并不只是因为它的哲学论证最合理，
更是因为它赋予每个人价值，这一点在政治、经济和军事上大有好处。

目前的科学反馈可以概括为三项原则：
+ 生物是算法(有机算法的集合）
+ 算法的运行不受组成物质的影响
+ 非有机算法可以复制甚至超越有机算法

随着算法将人类挤出就业市场，财富和权力可以集中在拥有强大算法的极少数精英手中，造成前所未有的社会和政治不平等。

社会系统将会更了解人类，并为他们做出大多数重大决定。

自由主义的三个信念：
+ 我是一个不可分割的个体
+ 真正的自我是完全自由的
+ 因此我能够了解一些别人发现不了的自我

生命科学对这三个假设提出了挑战：
+ 生物就是算法
+ 构成人类的算法并不自由，而是由基因和环境压力塑造
+ 因此，外部算法在理论上可能更了解我自己
** The Ocean of Consciousness
数据主义认为人类已经完成了自己伟大的宇宙任务，现在应该把接力棒交给完全不同的实体。

科技人文主义同意，我们所知的智人已经成为历史，以后不再那么重要，因此我们该运用科技创造出神人：一种更优秀的人类形式。

科技人文主义梦想推动的第二次认知革命，则可能对人类造成一样的效果，让社会大机器里的“人类小齿轮”沟通和处理数据的效率更高，
但几乎不会去注意其他事，不会做梦，也不会怀疑。
** The Data Religion
数据主义认为，宇宙是由数据流组成，任何现象或实体的价值就在对数据处理的贡献。

数据主义认为数据的流量已经大到非人所能处理，人类无法再将数据转化为信息，更不用说转化为知识或智能。

数据主义认为，人类的体验并不神圣，智人并非造物主的巅峰之作，也不是未来神人的前身。

数据主义的戒命：
+ 数据主义者要连接越来越多的媒体，产生和使用越来越多的信息，让数据流最大化。
+ 把一切连接到系统
+ 信息自由就是最高的善

数据主义者并不反对人文主义，数据主义对人类的体验并没有什么恶意，只是并不认为经验在本质上有何价值。

与未来相关的三项发展：
+ 科学正逐渐聚合在一个无所不包的教条之中，也就是认为所有生物都是算法，而生命则是进行数据处理。
+ 智能正有意识脱钩。
+ 无意识但具备高度智能的算法，可能很快比我们更了解我们自己。
