* The New Human Agenda
** old
*** The Biological Poverty Line
**** 以往
大多数人类生活在贫困线附近。一个小的疏忽或一点厄运都会对整个家庭和村庄宣告死亡。
在社会层面上不幸和愚昧造成了大量的饥荒。
**** 现状
在过去的一百年见，技术、经济和政治的发展在人类和生物学的平均线之间创造了越来越牢固的安全网。

现代的个人保险机制、政府机构和国际NGO虽然不会使危险人群免于贫困，
但会使他们不会死于饥饿。

即使在战争或自然灾害发生时，国际援助的介入也能狗成功防止饥荒。

在社会层面上全球贸易网络使干旱和食品成为了商业机会，并且使克服食品短缺更快更便宜。

当前在大多数国家，过度饮食成为了比贫困更严重的问题。在
2010年饥荒和营养不良一共杀死了一百万人，与此同时肥胖杀死了三百万人。

*** Invisible Armadas(plagues, infectious diseases)
**** 以往
从公元1330年开始在20年内席卷亚洲欧洲和北非的黑死病总共杀死了七千五百万到2亿人。

儿童因为缺乏免疫力，所以死亡率一直很高，大约三分之一的儿童会由于营养不良和疾病在成年之前死去。

**** 现状
二十世纪的医学取得了前所未有的成就，提供了疫苗、抗生素、加强的保健和更好的医疗设施。

儿童死亡率达到历史的最低点，仅为百分之五。

2002年SARS曾经引发了新世纪黑死病的恐惧，但是最终在全世界只造成了1000人的死亡。

*** Breaking the Law of the Jungle
在历史上，人类社会中和平是暂时的，而战争才是常态。

从20世纪后半页开始，在大多数地区战争越来越罕见。

**** 以往
在古农业社会百分之15的人类死于暴力，而在21世纪这个比例减少到了百分之1。

**** 现状
在2012年大约有五千六百万人去世，其中62万人死于暴力。相反有80万人死于自杀，
一百五十万人死于糖尿病。

核武器造成的恐怖平衡使得大国之间的战争更像是集体自杀。
同时全球经济也由资源型经济转变为知识型经济，使得战争带来的经济利益急剧下降。
战争也渐渐的局限在落后的资源型经济体之间。

恐怖主义就像瓷器店里的苍蝇（牛）--依靠制造混乱来造成破坏。
** new
* PART1 Homo Sapiens Conquers the World
** The Anthropocene
** The Human Spark

* PARTII Homo Sapiens Gives Meaning to the World
** The Storytellers
** The Odd Couple
** The Modern Covenant
** The Humanist Revolution

* PARTIII Homo Sapiens Loses Control
** The Time Bomb in the Laboratory
** The Great Decoupling
** The Ocean of Consciousness
** The Data Religion
