* 产出
GDP:一国在某一给定年度内所产生的所有最终产品和劳务的市场价值。

计算国民产出的一个核心问题就是要避免同一种产出的重复计算。
+ 附加值法
+ 支出法-最终销售额
+ 收入法

一国的产出因此就代表着它最终的预算限制，
这就是为什么国民产出这个概念在宏观经济学中处于核心地位的原因所在。

对于有贸易赤字的国家来说，关键问题是它们能否合理利用这笔额外的产出；
而对于有盈余的国家来说，能否现在让度给其他国家的这部分产出在未来受到好的回报才是问题的关键之处。

增长的来源：
+ 劳动的增加
+ 资本的增加
+ 使用两种要素的效率的提高

从根本上来讲，大多数金融资产都代表这对实际生产性资产的求偿权，
而这些生产性资产预计将在未来带来产出。

资本源自生产，而产出是通向目的的手段--
目的是在未来生产出更多的产出。

* 货币
市场经济中，货币可以实现多重目标，其最基本的目标之一
就是促进交易的实现。

宏观经济学家最感兴趣的三个变量：
+ 利率：货币的价格-投资资金的成本（货币的时间价值）
+ 汇率：一种货币相对于另一种货币的价格
+ 价格总水平：用货币来计量的所有产品和服务的平均价格。

实际汇率变动的关键在于国内通货膨胀的上升的幅度是否大于汇率下降的幅度；
或者更具体的说，国内和国外通货膨胀率之间的差异是否大于本币相对于外币贬值的幅度。

* 预期
预期可以推动经济朝着这样或那样的方向前进，
甚至可能自我实现。

事实上，对预期进行管理，是宏观经济政策（包括货币政策和财政政策）中最重要的职能。

积极的预期可能有助于使衰退的经济恢复到潜在的水平。
但是，一旦潜在水平已经达到了，
国家的各个行业已经重新回到无闲置的状态，
进一步的积极和乐观只能导致通货膨胀，而不是实际增长的进一步加速。

* 美国货币及货币政策简史
在建立一个新国家的过程中，政府官员的首要任务之一就是确定记账单位，
即为了满足会计和交易目的而确立的标准公制单位。

正如经济学家所确信的，真正需要保持稳定的东西是美元相对于作为总体的产品和劳务（产出）的购买力，
而不是专门保持黄金的稳定，显然货币政策不得不变。

* GDP核算的基本原理
用技术术语来讲，GDP不包括从国外赚得的净收入额，
而GNP（国民生产总值）包括。

GDP核算不仅能够告诉我们当前投资的价值，
也让我们能够识别这些投资是通过什么渠道获得资金的。

* 解读国际收支平衡表
国际收支平衡表记录了一国从事跨国交易的基本情况。

一个BOP表包含下面几个项目：
+ 经常账户余额:商品和服务贸易余额，净收入，净单边转移
+ 资本和金融账户：净资本账户，金融账户，其他资本流动，官方储备的变动
+ 误差和遗漏（统计误差）

借方和贷方
负债和求偿权

* 理解汇率
+ 短期变动看利率
+ 中期变动看通货膨胀
+ 长期变动看经常账户的不平衡情况
