* 人际关系的构成
** 亲密关系的性质和重要性
*** 亲密关系的性质
+ 了解程度
+ 关心程度
+ 相互依赖性：彼此需要的程度和影响对方的程度（特征：频繁、强烈、多样和持久）
+ 相互一致性：自我接纳他人的程度是测量一致性最生动、直接的方法。
+ 信任度
+ 忠诚度

*** 归属的需要
归属是人类长期演化的产物。

如果我们要正常地生活和保持身心健康，就需要在长久、关爱的亲密关系中经常与伴侣愉快地交往。

** 文化的影响
文化标准是人们建立人际关系的基石，它影响着人际关系的期望，限定了正常的人际关系模式。

*** 亲密关系变化的根源
影响人际关系规范更重要的因素是特定文化下青年男女的相对数量-性别比率。

原因可能是：社会规范的演变总是满足那些掌握经济、政治和法律权力的强势人群的利益。

** 个人经历的影响
依恋类型：安全型、痴迷型、疏离型和恐惧型。

个人经验在塑造人际关系的依恋类型上有着重要的作用。

尽管依恋类型能够改变，但他们一旦确定后，既稳定又持久，并影响着人们建立新的人际关系，加强已有的行为倾向。

** 个体差异的影响
*** 性别差异
+ 有些两性的差异的确存在，但非常小。
+ 男人或女人性别内的行为和观点差异远大于两性之间的平均差异。

*** 性认同差异
性认同差异指的是由文化和教育引起的两性在社会性和心理上的差异，或者叫社会性别。

把与任务有关的“男子气”的才能称为工具性特质，
把与社交和情感有关的“女人味”的技能称为表达性特质。

正是这些差异“实际上造成了很多不和谐”，最终导致人际关系的失败。

约有三分之一的男性也像女性一样温情脉脉、亲切体贴和敏感细腻。
而不具备这些特点的男性也可能通过学习，变得比现在更加热情，更加具有表达性。

*** 人格
人格特质较稳定，长期也只会缓慢地变化。

最终要的人格特质可能是那个有消极作用的特质：神经质。

*** 自尊
对自我的评价构成了自尊。

社会测量学具有启发性的主导理论认为，自尊是人们的主观计量器，即“社会关系测量学”，测量我们与他人人际关系的质量。

低自尊的人有时低估伴侣对他们的爱，从而损害亲密关系，还觉知到根本就不存在的伴侣的漠视。

** 人类本性的影响
演化学的三个基本假设：
+ 性选择使人类成为今天的物种。
+ 两性之间之所以存有差异，只是因为某种程度上他们在过去面临着不同的繁殖困境。
+ 文化影响决定了演化形成的行为模式是否具有适应性-并且文化的变化比演化快的多。

演化学原理认为：任何普遍的心理机制之所以以它目前的形式存在，是因为它一直在帮助人类解决过去的生存或繁殖问题。

通过识别人类共有的行为模式来描绘人类的本性，是演化学视角最令人信服的研究领域之一。

** 人际互动的影响

** 人际关系的消极面

* 研究方法
探讨某个特定研究课题的方法很多，各有其利弊。
真正的科学家会系统而认真地收集和评价各种信息，但没有任何一个单一的研究方法能得出绝对明确的答案。
** 问题的提出
亲密关系所涉及的问题来自所有这些根源：
科学家把他们自己的个人观察、他们对社会问题的认识、他们对前人研究的了解以及
他们自己的理论视角结合在一起去挖掘要回答的问题。

问题的分类:
+ 对某些事件或一系列事件的自然发生过程进行描述。
+ 确定事件之间的因果关系，以确定哪些事件对随后的结果有显著的影响，哪些没有。

不同的研究有不同的目的。如果某项探索性实验是为了描述新发现的现象，我们不应该因为它确定不了因果联系而去苛责。

不要试图从以描述为目的的研究中得出因果联系。

** 被试的选取
+ 方便取样
+ 代表性取样：确保被试与研究的整个总体之间的相似性。

不过人际关系的研究者所考察的许多过程非常基础，在人口统计学上不同的人群间在此方面并不存在过大的差异。

** 研究的设计
*** 相关设计
相关的存在意味着可能有很多不同的似是而非的因果关联。

运用高级统计技术却有可能在相关设计的结果上得出一些因果联系的可靠结论。

*** 实验设计
实验提供了原因和结果的最直接了当的结论，因为实验者创造并控制了他们研究的条件。

在真实验中，研究者有意操作一个或多个变量，并把被试随机分配到这些事先创造的不同条件下，
从而观察这些条件变化怎么影响人们的行为。

*** 发展性研究设计
发展性研究设计研究行为或事件随时间而改变的方式。

**** 横断研究设计
比较处在不同人生阶段或者不同年龄者的发展过程。

某些不确定性的影响：所经历的不同社会、文化和政治事件。

**** 纵向研究设计
对同一人群在一段时间内反复进行测量。

不确定性的影响：
+ 社会文化的巨大变化仍然会混淆年龄和经验的影响。
+ 被试流失。

**** 回朔研究设计
在时间上往回走。

不确定性的影响：记忆和认知偏差。

** 场景的选择
实验室和自然场景的优缺点恰好互补。

*** 实验室
**** 优点
+ 能有效控制外在的、无关变量的影响。
+ 能精确控制被试要经历的体验，还能安排符合研究目的的物质环境

**** 缺点
可能引发被试的虚假行为，使我们对他们的认识不足。

*** 自然场景
**** 优点
被试在日常的环境中感到舒适和放松，从而使实验者可能引发而获得更多的典型行为。

**** 缺点
自然场景可能充满了与研究问题无关的干扰变量。

** 数据的性质
无论我们采用何种数据，对行为的测量应该同时具备心理测量学上的效度（我们测量到的事件是我们真正试图测量的）和
信度（如果这些事件不会发生变化，我们在不同时间的测量结果应该一样）。

*** 自我报告
自我报告有着重要的价值：
+ 能告诉我们人际关系事件对当事人的意义。

**** 潜在的问题
+ 被试对问题的解释
+ 回忆或觉知的困难
+ 被试报告的偏差（自我服务偏差，社会赞许性偏差）

*** 观察法
科学观察并不是轻松随意的工作。研究者要么采用复杂的工具测量行为，要么细心地训练助手以使观察尽量准确、可靠和详尽。

**** 观察方法
+ 直接观察正在发生的行为
+ 采用记录设备

**** 存在的问题
反应性问题：如果人们知道自己正在被观察就会改变自己的行为。

*** 生理测量
如果我们观察的行为是人们无法有意识地加以控制的，就可以避免反应性问题发生。
对人体自主的和生化的反应进行生理测量就能做到这一点。

生理测量一般成本较高，但其应用在不断增加，因为生理测量能让研究者考察我们行为的生理根源和社会根源之间的重要关系。

*** 档案材料

*** 夫妇报告
夫妇任何一方都要报告自己的行为，同时也是伴侣行为的观察者。

** 研究应遵循的道德规范
科学在道义上必须履行的责任是求得真知造福人类。

** 结果的解释和整合
如果心理学、社会学或传播学研究的结果具有统计学上的显著性，这表明这种结果不太可能随即发生，但不是完全不可能随即发生。

像科学家那样思考：
没有一项研究是完美无缺的，但真理就在前方。我们更相信不同的科学家采用不同的被试样本研究得出的结果。
如果研究结果用不同的方法得到重发，我们就更有信心。

元分析：
研究者把针对某一特定现象的所有现存研究汇编到一起，分析整合它们的结果以识别它们的共同规律。

* 吸引力
** 吸引力的基础：一种奖赏
人与人之间产生吸引力最基本的假设是：
他人的出现对于我们有奖赏意义。

影响吸引力的奖赏有两种类型：
与他人交往产生的直接奖赏，和仅与他人有关的间接利益。

** 临近：喜欢身边的人
*** 方便：远亲不如近邻
如果他人在我们身边，我们很容易得到他们提供的各种奖赏。

*** 熟识：重复接触
曝光效应：
刺激的简单暴露能够提高个体的态度体验，人们对他人或事物的态度随着接触次数的增加而变得更积极的一种现象。

*** 临近的作用
临近能增强我们对他人的情感。如果我们与他人相处愉快，当他们在身边时我们会更喜欢他们。
然而，如果我们讨厌某人，临近只会使事情变得更糟糕。

** 长相吸引力：喜欢那些可爱的人
*** 吸引力的刻板印象
外貌吸引力的刻板印象普遍存在，但俊美之人有哪些优势，一定程度上取决于具体文化所强调的价值观。
但也容易被认为较放荡。

*** 吸引力的秘密
对是否美丽所判断的一致性要远大于分歧性。并且这种共识是跨种族的。

面孔：对称和“平均”

身材：腰臀比

*** 长期吸引力的演化观

*** 文化也起作用
人类本性和环境条件一起塑造了我们对美丑的共同判断标准。
我们常常被那些看起来是个好配偶的人所吸引，但具备什么样的条件才算是好配偶，一定程度上依赖于我们所居住的环境。

*** 对美丽持有偏见的人
在全世界，男性比女性更为关注恋人的长相吸引力。

高自我监控（人们为适应不同的情境而调控自己行为的能力）的男性特别关注恋爱伴侣的俊美长相。

*** 美丽：交织着的代价与收益
女人的美貌和她与男人交往的时间整体上看并无相关。

男人的长相和他们与女人交往的次数和时间存在相关。

俊美之人常常能与别人愉快的交往，但不如长相平庸的人那样信任别人。

*** 长相吸引力的匹配
亲密关系越正规严肃、投入程度越多时，匹配程度就越明显。

** 礼尚往来：喜欢那些喜欢我们的人
对未来伴侣的期望值=伴侣的长相吸引力×伴侣接纳自己的可能性

我们期望伴侣接纳自己的可能性大小，很大程度上和自己的适配价值即作为生殖伙伴的综合吸引力有关。

喜欢那些喜欢我们的人不仅符合吸引力的奖赏模型，还符合平衡理论：人们期望他们的思想、感情和社交关系能够保持一致。

** 相似性：喜欢与我们相像的人
人际关系最基本的原则之一就是相像律：相类似的人彼此吸引对方。

有吸引力的相像种类体现在各个方面，共同点越多，彼此越喜欢。

匹配是广泛的过程，有时人们是在用一种优势交换伴侣的另一种优势，但双方却有着类似的适配价值。

知觉到的相像程度和婚姻满意度之间的相关高于真实的相像和婚姻幸福之间的相关。

某些相像比其他相像更重要。

差异可能随着时间而减少。

我们喜欢那些与我们理想自我相像的人。

互补性存在于伴侣双方的不同行为：支配与顺从。

*** 亲密关系的三个不同阶段
刺激-价值观-角色

时间和经验的影响还表现在致命的吸引：如果伴侣最初吸引人的品质逐渐变成最惹人厌烦、烦恼的特点，致命的吸引就产生了。

*** 相像具有吸引力的原因
提醒我们这样是没有问题的。

** 障碍：得不到的就喜欢
罗密欧与朱丽叶效应：父母越是干涉子女的恋爱自由，他们彼此之间就越会相爱。

打烊效应：得不到的禁果格外甜。

** 男女两性的理想伴侣
+ 热情和忠诚
+ 吸引力和活力
+ 社会地位和资源

*** 性别差异
男人往往确保女友有普通的长相，
女人往往确保男友有点金钱和前途。

* 社会认知
社会认知指我们理解社会现象的知觉和判断过程。

** 第一印象
+ 把人们的注意力导向某类新信息
+ 影响对后来获得的新事实的解释

导致那些站不住脚的第一印象，改变起来也比理论上认为的要困难的多。

** 知觉的力量
*** 伴侣的理想化
危险性取决于积极错觉与现实的不符合程度有多大。

聪明的做法：
随着对伴侣了解程度的增加，不断调整自己对理想伴侣的期望。

*** 归因过程
+ 行动者/观察者偏差
+ 自利偏差
+ 依恋类型和神经质人格有着重要的影响
+ 伴侣双方总的归因模式能决定亲密关系的满意程度

*** 重构性记忆
共同的记忆是伴侣对新事物做出共同反应的基础。
伴侣们叙述的亲密历史故事，会影响后来现实生活中双方对交往所作出的解释。

*** 关系信念
+ 浪漫主义（1.与伴侣的爱情是完美无暇的;2.每个人只能有一个完美的真爱;3.真爱能克服一切障碍;4.一见钟情是可能存在的）
+ 宿命信念
+ 成长信念（幸福的关系是努力和付出的回报）

*** 期望
自我实现式的预言

*** 自我知觉
在恋人期，自我提升是很重要的动机;不过在相互依赖更多，更投入的人际关系中，自我证实占主导。

** 印象管理
+ 我们在他人面前做的几乎全部事情，其调控策略都是围绕着印象管理的
+ 它对人们生活有着广泛的影响

*** 印象管理策略
+ 逢迎讨好
+ 自我推销
+ 恐吓
+ 恳求

*** 亲密关系中的印象管理
+ 我们对好友和恋人制造的印象比为熟人或陌生人制造的更为重要，
但是为了维持良好的形象，我们在前者花的心思通常不如后者。

+ 亲密关系建立后，人们会为自己的好友营造讨人喜欢的公众形象。

+ 个体差异：自我监控能力。

** 我们了解伴侣的程度
+ 了解
+ 动机（结婚时间和情绪状态）
+ 伴侣的易理解性
+ 知觉者的能力
+ 危险的知觉（对伴侣令人不安的情感和行为变得愚钝）
+ 知觉者的影响（引导伴侣符合我们的想象）

* 沟通
人际隔阂：
传递者的意图和对接受者产生的影响并不相同。

** 非语言沟通
+ 提供信息
+ 调控交往
+ 界定人际关系

*** 非语言沟通的组成
+ 面部表情
+ 注视行为
+ 身体动作
+ 身体接触
+ 人际距离
+ 副语言（除了言语过程的词语之外，个体发出的各种声音特性）

如果人们的话语和动作之间存在不一致，言语背后的真实意图往往表现在非言语沟通当中。

*** 非语言沟通的敏感性
伴侣们运用非语言沟通的敏感性和准确度能预测他们亲密关系的幸福程度。
此外，如果出现这类问题，一般都是丈夫的错（技能和动机似乎都有关）。

*** 非语言沟通中的性别差异
从总体看，这些性别差异是十分醒目的：
在所有情况下，女性和男性的交往行为都映射出地位低的人与上司的交往方式。

** 言语沟通
*** 自我表露
自我表露指的是向他人透露个人信息的过程，它是亲密程度的指标之一：
如果两个人彼此之间不共同拥有一些私人的、相对秘密的信息，他们的关系就称不上亲密。

*** 社会渗透理论
大多数人际关系是以肤浅的信息交流为起点的，然后再逐渐转到更有意义的披露。（成楔形）

交往的最好的策略是经常保持耐心，让可以感觉到的相互作用逐渐地增加你们交往的亲密感。

对于持久的亲密关系来说，伴侣的应答性的作用更大。

*** 言语沟通中的性别差异
+ 交谈的话题
+ 谈话风格
+ 自我表露
+ 工具性对表达性（性别角色的刻板印象的影响）

** 沟通障碍及其应对
*** 沟通不良
*** 精确表述
当你在Y情境下做X时，我感到Z
*** 积极倾听
+ 复述
+ 知觉检验

*** 守礼而镇定
+ 只要有可能就要先允诺与伴侣彼此以礼相待，这也是减少使人愤怒的事件的好方法。
+ 如果你发现自己处在一种消极情感相互作用的状况，可以暂停下以打断这个恶性循环。

*** 尊重和确认的力量
对伴侣的确认，即承认他们观点的合理性，表达对他们立场的尊重，一直是亲密交往中值得拥有的目标。

* 相互依赖
** 社会交换
*** 奖赏和代价
社会交换理论宣称人们总在追求可能的最好结果（结果=奖赏-代价）。

*** 人际关系的期望收益
相互依赖关系假定每个人都有一个与众不同的比较水平（CL），即我们认为自己在与他人交往中应当得到的结果值。

满意度=结果-CL

*** 人际关系的替代收益
替代的比较水平（CL_alt）,确定了我们在其他的亲密关系中是否会更好。

个体的CL_alt是他主观认识的产物，从而存在一系列因素影响着人们对它的认识，
比如自尊，习得性无助。

依赖度=结果-CL_alt

*** 与时俱变的比较水平
因为比较水平是建立在我们过去经验的基础上，所以它往往会随着我们得到的关系结果而不断波动。

比如我们会把一些好处逐渐视为理所当然，CL_alt开始升高，我们的愉悦感减少。

** 亲密关系的经济论
亲密关系会纵容了伴侣间的无礼行为。

亲密关系中“坏的比好的更有力量”。

要保持满意的亲密关系，我们或许需要保持5：1的奖赏-代价比率。

奖赏和代价是彼此独立，各自相异的：
+接近动机：获得正面的结果。
+回避动机：避免负面的结果。

自我延伸模型：能扩展我们的兴趣、技能和经验的伴侣关系就能吸引我们。

*** 与时俱变的奖赏和代价
紊乱模型：
在亲密关系发展到中等程度的亲密度时，随着伴侣学会自己的需要和适应彼此，可能会出现一个调整和重新评价的动荡期。

约有三分之一的人不能轻松舒适地对待相互依赖的亲密感;
他们要么担心伴侣不够爱自己，要么在走得太亲近时感觉不自在。

人们不能维持步入婚姻时的那种亲密关系结果的原因：
+缺少努力
+相互依赖的放大镜作用
+对敏感信息武器的通达
+不受欢迎的意外
+不现实的期望

** 亲密关系中的贪婪
*** 相互依赖的实质
相互依赖理论认为，在追求美满的关系结果时，个体应经常对自己所依赖的人宽容大度，
因为给伴侣提供一个高水平的关系结果时，可以使他们想要留下来。
如果伴侣双方都想亲密关系持续，双方都应深思熟虑地保护和维持对方的幸福。

*** 交换关系和共有关系
交换的亲密关系受“给出的利益要即时得到偿还”这一欲望和期望的调控。

共有的亲密关系受到“对彼此需要的相互应答”这一欲望和期望的调控。

交换的观点似乎并不适合更亲密的关系，因为当伴侣们进展顺利时，
他们享受到“盈余经济”，似乎不太在意对方做得怎样。

*** 公平关系
人们只有在相称的公正前提下才对亲密关系最为满意。

你的关系结果/你的贡献=伴侣的关系结果/伴侣的关系贡献

人们得到的关系结果的总体质量和收益不足这两个方面，
在预测亲密关系的满意度和持续性上起着重要的作用。
但关系结果是比不公平更重要的因素。

** 忠诚的本质
对亲密伴侣的幸福依赖可以孕育忠诚，即持续亲密关系的意图。

三种类型的忠诚：
+个人忠诚，即人们受到伴侣的吸引、亲密关系令人满意，而希望关系继续时变现出的忠诚。
+强迫忠诚，即因为离开关系的代价过高，人们觉得不得不继续现有关系时表现出的忠诚。
+道德忠诚，来自对伴侣或者亲密关系的道德责任感

*** 忠诚引起的后果
长期来看，亲密关系需要付出的代价比我们预计得要大的多。

忠诚使人们采取行动以保护和维持亲密关系，即使这样做的代价很高。

忠诚会促进顺应性行为，人们会克制自己不以愤怒来对应对伴侣的愤怒。

忠诚的人还表现出更大程度的牺牲意愿，为了关系的融洽而牺牲自我利益。

忠诚到的人还表现出认识到的优越感--他们认为自己的亲密关系比别人的更好。

* 友谊
** 友谊的本质
友谊是我们与他人发生联系的重要方式，并且可以给我们带来快乐和兴奋。

*** 友谊的属性
友谊包含情感的、共有的和社交的要素。

**** 友谊和爱情的差异
除了对伙伴正面、热情的评价，
浪漫的爱情还包括对伴侣的着迷、性的欲望和比友谊强烈的多的排他性的愿望。

爱情关系还有着更严厉的行为标准;对待爱人应该比对朋友更加忠诚、范约束力较小，友谊更易于解体。

朋友不太可能会公开表达正面情感，他们一起相处的空闲时间也比情侣要少的多。

**** 尊敬

**** 信任

**** 应答性
对我们的需要和兴趣的关注与支持式的认可就是应答性，它具有很高的奖赏价值。

**** 资本化
在资本化的交往模式中，我们常常能和朋友分享好消息，得到对紧密关系有益的热心和有价值的反应。

**** 社会比较
我们还会将我们的观念与朋友比较，以便更好地理解我们自己。

嫉妒和分享喜悦。

**** 社会支持
***** 社会支持的形式
+表现为关爱、接纳和安慰等形式的感情支持
+表现为咨询和指导形式的建议支持
+表现为金钱或物品的物质支持或有形援助

***** 社会支持的价值
+感情支持具有实际的生理效应
+有效的社会支持使人们感到与帮助者更亲近
+人们所提供的支持的质量还会受到他们依恋类型的影响
+最好的支持应该切合我们的需要和偏好
+真正起作用的并非朋友具体的帮助行为，而是我们知觉到的朋友提供的帮助
+我们个人的特性也会影响我们对社会支持的知觉

*** 友谊的规则
大多数人都会有一套人际关系的规则，这种规则是朋友应（或不应）履行某些行为的共同文化信念。

** 友谊的毕生变化
随着人们年龄变大人际关系也会发生变化。成人应对友谊问题时丰富和复杂的方法都是历经岁月锤炼的结果。

*** 中年期
二元退缩现象：人们与爱人见面次数越来越多，而探望朋友的次数越来越少。

*** 老年期
老年人的交友更加挑剔，更注重满足自己的情感需要。

社会情绪选择理论：
友谊随年龄的这种变化是因为老年人有着与年轻人不同的人际目标。

** 友谊的差异
*** 友谊的性别差异
女性的友谊是“面对面”的，男性的友谊是“肩并肩”的。

*** 友谊的个体差异
+自我监控
+亲密需要
+关系型自我构念：指人们在多大程度上把自己看成是与他人相互依赖的人

** 友谊发展的障碍
*** 羞怯
**** 羞怯在社交情境中有三种表现
+紧张不安
+寡言少语
+拘谨压抑

**** 羞怯者的三个特征
+害怕别人的负面评价
+怀疑自我
+感到自己能力不足

**** 改善方法
给自己更多的镇静和自信

*** 孤独
如果我们所期待的人际关系数量和质量与我们当前实际情况存在较大差距，
就会产生令人不悦的厌烦、悲痛和绝望的孤独体验。

**** 两种孤独的困扰
+社会隔离：缺少朋友和熟人的社交网络而引起的孤独
+情感隔离：我们缺乏深厚的人际关系而引起的孤独

**** 孤独的来源
+人与人之间孤独的变异约有一半来自基因的影响
+孤独受到个人特征的影响：依恋类型，自尊
+性别：平均而言男性比女性更孤独

**** 孤独的危害
孤独会对健康造成伤害

孤独还会引发抑郁

**** 改善方法
如果你能采用更积极的方法-关注他人的优秀品质，期望他们愉悦友善，
并且耐心地承认友谊的建立需要花费时间-你就可能会享有与他人更有价值的交往。

* 爱情
** 爱情简史
通过文化和历史差异的比较，发现爱情的形式多种多样。

** 爱情类型
*** 爱情三角理论
爱情的三个成分：
+亲密：热情、理解、沟通、支持和分享
+激情：性的唤醒和欲望
+忠诚：投身于爱情和努力维持爱情的决心

爱情的四种形态：
+浪漫之爱
+相伴之爱
+愚昧之爱
+完美之爱

我们天生就具有演化而来的三个不同的生理系统，
它们各自促进了人们的成功繁殖过程-它们也支持了这样一种可能的结果：
激情、亲密和忠诚的体验彼此相当独立，在任何时间都能独自地发生强弱变化。
另一方面，在很多爱情关系中，亲密、激情和忠诚的情感体验又相互有着明显的关联。

*** 浪漫狂热之爱
任何形式的强烈感情，无论好坏，都会影响我们对浪漫爱情的感受。

**** 唤醒
激情洋溢的吸引力根源于两个因素：
+生理唤醒，如心跳加速
+相信另一个人是引起你唤醒的原因

**** 思维
“爱情是盲目的”：人们会低估或忽视爱侶的缺点。
他们将爱侶的形象理想化，这与他们面对的具体事实有着重大的差别。

浪漫且充满激情的爱情所具有的唤醒和认知特性包含了波涛汹涌的感情、想象力和理想化，
有时还会出现痴迷的情形。
*** 相伴之爱
相伴之爱并不依赖激情，所以它比浪漫之爱更为稳定。

催产素的释放似乎是相伴之爱产生的生物基础。

*** 爱恋风格
六种爱情风格：
+情欲之爱
+游戏之爱
+友谊之爱
+狂热之爱
+利他之爱
+现实之爱

男性在游戏之爱上得分更高，而女性更偏向于友谊之爱和现实之爱。

对爱情持有相似态度的人更容易成双配对。

** 爱情的个体差异
*** 依恋类型
安全型的人体验到更强烈的浪漫之爱、相伴之爱和同情之爱。

依恋类型强烈、持久的影响表明人们不仅会拥有不同类型的爱情，
而且还会拥有不同类型的爱人。

*** 年龄
多数人会变得更加成熟。

*** 性别
在爱情的三个成分中，激情与男性关系的满意程度有着很高的关联，
而忠诚则是预测女性满意度的最好成分。

** 爱情很难持续
人们在结婚之后浪漫的爱情会减弱。
随着时间的流逝，人们在浪漫和爱之激情量表上的得分都会下降。

*** 浪漫爱情难以持久的原因
+幻想
+新奇
+唤醒

*** 爱情的未来
享受激情，但不要把它作为维持爱情关系的基础。培养与爱人之间的友谊。
努力保持新鲜感;把握住每一个与配偶共同进行新奇探索的机会。

如果对爱人急迫的欲望渐渐演变为平静而深厚的情感，不要觉得奇怪或失望。
这种幸福的结果可能会让你成为幸运的爱人。

* 性爱
** 性态度
*** 对随意性行为的态度
只要未婚的伴侣是在忠诚的爱情基础上发生性行为，就可以得到容许。
但亲密关系中的依恋和情感仍然被公认为是性行为最恰当的前提。

但社会对男性和女性在性宽容的标准上存在双重标准。

*** 对同性恋的态度
人们对同性恋的评价与他们对个体成为男同或女同的原因的理解有着密切的关联。

*** 性态度上的文化差异
时代在变，但美国人的性态度仍然比较保守。

** 性行为
亲密关系中性行为最重要的特点是：
性行为为伴侣双方所期待，并且双方都能得到满足。

*** 第一次性行为
女性比男性在第一次性行为时会更可能有矛盾的情感。
而且男性比女性更可能后悔没有与某个人发生性行为。

*** 忠诚关系中的性行为
**** 发生性行为的理由
+情感成分
+肉欲成分
+实用的理由：实现某些长远目标或具体愿望
+不安的理由：提高个体的自尊等

**** 性行为频率的影响因素
+亲密关系的性质
+个体的年龄
+性取向

*** 不贞
男性更可能追求伴侣外性行为，女性更可能找寻感情上的联系。

比性别差异更重要的是个体差异：
社会性行为取向，它是一种类似人格特质的信念，可以用来描述个体对性行为的看法。

**** 女性出轨的解释
优质基因假说：
+能追求到长期的伴侣，为她们提供保护和喂养后代的资源。
+暗中从其他男性那里为她们的后代寻找优质的基因

伴侣关系的当前质量

*** 性欲望
男性对性行为的更多兴趣可能使最小利益原则发生作用：
女性控制了男性想要的事物的使用权利，这让她们拥有了影响男性的力量。

*** 安全明智的性行为
**** 低估了不安全性行为的风险
特殊安全错觉：
大多数人都会认为不幸的事件通常更可能发生在别人身上，而自己不会这么倒霉，
所以我们不会采取明智的预防措施，以避免可以预计到的危险。

**** 错误决策
+性唤醒
+酒精近视：醉酒后思考和加工信息的能力会降低。
**** 人众无知
如果人们错误地认为他们的情感和信念与其他人不一样，就会产生人众无知。

**** 权力不等
**** 禁欲教育
**** 亲密感和愉悦度的减少
在所有影响安全性行为的因素中，最重要的阻碍或许是，
如果人们不使用避孕套通常能更好地享受性生活。

** 性满足
人们在性行为表现固然重要，但人们对这些行动的感受更有影响力。

根据自我决定理论，无论性行为的频率如何，只要它能实现人类对自主、能力和交往的基本需要，
性的互动就最有奖赏价值。

传统性别角色的规定看来同时剥夺了男女双方的某些性自由和性放任，
致使他们的性互动达不到原本可能的满足程度;
彼此允许更多自主权和选择权的夫妻能享受到更为满足的性生活。

*** 性沟通
在性行为上的积极沟通是与更高的性满足联系在一起。

*** 性满足与关系满意度
有着美好性生活的亲密关系往往更令人满意;
对伴侣的爱意也使得性生活更有奖赏价值。

美好的性生活还依赖于：
+个体特殊的性欲望能得到伴侣的理解和尊重
+重视自己的伴侣并致力于维护好伴侣关系
+愉快地彼此相处，无论是在床上还是床下

** 性胁迫
如果伴侣一方在违背另一方意志的情况下，故意哄骗、引诱、威胁或强制对方
与之发生性接触，则会损害伴侣的性互动和伴侣关系。

**** 减少性胁迫发生的建议
+当心把性行为看作角逐某种利益的恋爱对象
+远离麻醉类物品
+下决心坚定地反抗任何性侵犯的苗头
+在开始交往前，直接、坦率地划清界限

* 压力与紧张
负面事件的出现，表明我们得不到伴侣的爱慕和尊敬

** 关系评价
我们在知觉到他人认为与我们的亲密关系珍贵、重要或亲近的程度--
低于我们的期望时就会感到苦恼。

** 感情创伤
精细区分不同的接纳程度而不是拒绝程度能让我们得到更多的生存资源和交配机会。

关系贬值带给人的感受尤为可怕，会引起多种痛苦的情绪反应。

** 伴侣排斥
人们具体的反应取决于个体的哪种需要受到威胁：
+归属感--重新获取伴侣的尊敬或寻找更宽容的伴侣
+控制欲/价值观--敌对的反应

** 嫉妒
嫉妒包含多种情感类型，既有悲观失落也有因伴侣具有吸引力而产生的自豪感，
但界定嫉妒最恰当的三种情感是：伤害、愤怒和恐惧。

嫉妒更像是一把双刃剑，
一方面传递着浓情蜜意，
另一方面却是偏执狂的表现。

*** 嫉妒的两种类型
+反应性嫉妒：人们在觉察到自己所珍视的亲密关系面临实际威胁时产生的嫉妒心理。
+怀疑性嫉妒：伴侣并没有不端行为，个体只是由猜疑所引起的嫉妒。

*** 容易嫉妒的人
+适配价值存在差距的人--门当户对
+依恋类型
+人格特质：神经质
+传统的性别角色

*** 让人嫉妒的人
具有较高适配价值和使我们相形见拙的人：
+男性更嫉妒自信、强势、果断和富有的情敌
+女性更嫉妒比自己漂亮的情敌

*** 让人嫉妒的事物
演化学的观点认为嫉妒的演化能促使我们采取一定的行为，
以保护自己的亲密关系免受他人的侵袭。

这方面的研究结果和许多其他研究一样，
两性之间彼此的相似性要远多于差异性。
不过在某种意义上两性毕竟存在差异，男性对伴侣性事上的不贞有强烈的嫉妒，
而女性对伴侣感情上的不贞反应更强烈。

*** 对嫉妒的反应
依恋类型能决定人们应对嫉妒的行为

女性似乎关注于维护好现有的亲密关系，而男性则会考虑离开，
通过征服新的恋人来医治受伤的自尊。

女性比男性更有可能设法引起伴侣的嫉妒。

*** 积极有效地应对嫉妒
两个策略：
+依靠自己
+支持自己

警示：
不论你是否拥有自己伴侣的爱恋，如果你不能确信自己是个有价值的人，
那么这很可能危及你和伴侣的健康。

** 欺骗和说谎
*** 亲密关系和普通关系中的说谎行为
我们更多地在亲密关系里对伴侣撒下弥天大谎，
而在普通的人际关系中则不会这样。

欺骗者猜疑：
当人们对别人说谎时，他们经常会认为谎言的接受者也因此不值得信任。

说谎者认为他们的谎言更加无害，更加没有冒犯意义。

伴侣的不正当行为的接受者几乎总是认为这种行为包含更多的信息，更加有影响力。

*** 谎言与说谎者
+吞吞吐吐
+瞳孔扩大，频繁眨眼
+微格表情
+语调和面部表情不匹配
+个体的副语言和身体紧张

*** 对伴侣欺骗行为的觉察
我们据以判断他人说谎或许非常具有特异性。

随着亲密关系变得更加亲密，信任也在增加，伴侣们察觉彼此欺骗的准确性却有减无增。

** 背叛
我们信任的人做出的讨厌的、伤害人的行为，并且在情理上我们根本预期不到这种背信弃义的不端行为。

即使人们意图良善，也完全无法承担由于亲密和相互依赖所产生的相互交疊和竞争性需求，
这时就会发生感觉式背叛。

*** 背叛的个体差异
那些报告屡次背叛别人的人生活悲惨、适应不良。

*** 背叛的两面性
背叛亲密关系的人通常会低估其背叛行为所造成的危害

被背叛的伴侣对越轨行为的后果评判更为严重

*** 应对背叛
+勇敢地正视背叛而不否认它的存在
+以积极的眼光重新解释背叛，并把它作为促进个人成长的动力
+依靠朋友，寻求支持

** 宽恕
宽恕是“一种针对曾不公平对待你的人，放弃你的报复的决定”

宽恕的重要构成要素：
+谦卑、真诚的道歉
+受害一方的共情作用
+受害者不要耿耿于怀

真正的宽恕对接收方和给予方都有益，在那些亲密、满意、最值得挽救的亲密关系中最容易得到。

* 冲突
伴侣待在一起的时间越长，要协调的活动和任务种类越广泛，
冲突就越可能发生。

** 冲突的性质
*** 冲突的定义
每当个体的动机、目标、信念、观点或行为妨碍别人，或者与别人矛盾时，
就会发生人际冲突。

冲突是不可避免的：
+任何两个人在情绪和偏好上都会不时地存在差别
+因为在亲密关系中交织着一定的张力，它们迟早会引起一些紧张

*** 冲突的频率
影响因素：
+人格
+依恋类型
+生命阶段
+相似性
+酒精

** 冲突的过程
*** 激发事件
夫妻双方在任何问题上都可能发生分歧。

*** 归因
任何两个人在社会交往中都会持有不同的视角，这往往是引起愤怒争执的另一个根源：
+行动者/观察者效应
+自利偏差
+男性比女性更可能把冲突判断为故意背叛和轻蔑信号

*** 介入和升级
只有伴侣双方都希望避开争端，才能避免冲突：
+激发事件微不足道
+争端很难处理，冲突没有任何好处

伴侣一方暴躁易怒惯常地也会伴侣另一方（至少某种程度上）变得愤怒。

冲突过猛或过频通常都会影响身体和心理健康。

*** 接近/退避模式
接近/退避模式，具体表现为“一方（接近者）批评、不断唠叨、向另一方提出要求，
而伴侣（退避者）逃避正面接触、退避、采取守势。

女性接近而男性退避的原因：
+性认同差异
+社会结构假说：男性在恋爱关系中拥有更多的权力

*** 协商和顺应
四种应对冲突的类型：
+讨论
+忠诚
+离开
+忽视

依恋类型、性别角色和社会文化等都会影响人们的选择策略。

顺应：当伴侣作出破坏性的行动时，顺应就是避免做出以眼还眼的冲动，
努力以建设性的态度做出讨论或忠诚反应。

*** 应对冲突：四类夫妻
争论到底能促进还是侵蚀伴侣的满意度，取决于两个重要的影响因素：
+伴侣偏好的相似性
+争议进行的方式

四种冲突的类型：
+多变型--夫妻会发生频繁、激烈的争论，但能充分应用智慧和真诚来缓和愤怒
+确认型--常常通过表达共情、理解对方的观点来确认彼此的观点
+逃避型--回避正面冲突
+敌对型

只要伴侣双方偏爱相同的冲突方式，彼此能保持高度的尊敬，
就算争斗激烈也无损于亲密关系。

** 冲突的结果
*** 冲突的结束
+分离
+支配
+妥协
+整合一致：指具有创造性、灵活性地满足双方最初的目标和期望
+结构性改善：指伴侣不仅得到他们想要的，而且从中得到学习和成长，使他们的关系发生可喜的变化

*** 冲突的益处
伴侣们未表达出的烦心事和引起愤怒的刺激物越多，他们往往对自己的亲密关系越不满意。

冲突能暴露存在的争端和矛盾，这样才有可能寻求解决方法。

避开脾气暴躁、态度恶劣的交往有一个非常好的方法，
那就是运用婚姻问题专家传授的技术来建设性地处理冲突，比如说话者-听话者技术。

* 权力和暴力
社交权力指的是影响他人行为并抵制他人影响自己的一种能力。

** 权力和相互依赖
*** 权力的来源
根据相互依赖理论，权力是建立在对有价值资源的控制的基础上：
+他/她只要拥有控制人们获得这些资源的能力就已足够
+所渴望资源的替代来源是否很容易获得

控制伴侣的关系结果：
+命运控制
+行为控制：个体能通过改变自己的行为来鼓励伴侣朝着理想的方向来改变他/她的行动的行为控制。

*** 资源的类型
+奖赏权力
+强迫权力
+合理权力：权威或公平、相互作用、社会责任等规范
+参照权力：尊重和爱戴
+专家权力
+信息权力

*** 男女两性和资源的控制
在整个人类的历史中，男性比女性享有的权力更多：
+男性和女性有着相对资源的差异：男性有着更多的金钱和地位，女性则是更多的爱恋
+社会规范支持并维护男性的支配地位

*** 权力的过程
拥有权力的人有着更多的正面情绪和自尊，当他们渴望的事物出现时，往往会主动采取行动。
而没有权力的人会显得更加谨慎，会更加焦虑地关注别人的表现。

**** 语言
男女两性在与同性伙伴的谈话时行为表现类似，
但与异性互动时则出现明显不同的模式，男性出现更多的打断别人和控制发言权的行为。

**** 非语言行为
女性对女性使用权威性的行为才能得偿所愿，而这类行为对待男性则很少能成功。

**** 非语言的敏感性
女性在判断他人情绪和意图方面一般比男性更精确。
但这种实用、合意的才能或许使得刻板模式继续存在。

*** 权力的风格
+直接的和间接的提出自己的愿望或要求，人们对自己的亲密关系越满意越可能采用直接的策略
+人们追求目标时与伴侣互动的程度，高权力的人等多的采用双边策略

个体的选择策略更多地受到他/她在特定交往中的地位而非性别角色的影响

*** 权力的结果
男性的自主、断言和女性的遵守、听从对于很多人而言似乎如此自然，以致他们很难发现这种类型的权力不平衡。

当伴侣双方所起的作用相等时，亲密关系整体看来更为稳定和幸福。

*** 权力的两面性
忠诚、幸福的爱人常常利用他们的影响力来使伴侣获益，从而提升他们之间的亲密关系。

然而权利也有其阴暗的一面。有些人，尤其是男性，努力想成为他们亲密关系中的胜利者。

** 亲密关系中的暴力
当我们故意造成他人身体伤害时，我们就在使用暴力作恶。

*** 暴力的普遍性
在美国进行的調查研究发现，每6对伴侣就会有1对发生某种形式的暴力。

*** 伴侣暴力的种类
+情境性暴力：它一般是从失去控制的剧烈冲突中喷发而出的
+亲密恐吓：伴侣一方把暴力作为控制和压迫另一方的工具
+暴力抵抗：伴侣有力地亲密恐吓进行反击

*** 伴侣暴力的性别差异
女性看来和男性一样具有暴力倾向，但她们不太可能造成身体受伤，
也不太可能利用暴力作为持续影响和支配他人的工具。

*** 暴力的相关因素
**** 情境性伴侣暴力
影响因素：
+激发因素
+促进因素
+抑制因素

情境性伴侣暴力所发生的环境既受到稳定而持续的倾向性和背景性因素的影响，
又受到更为短暂的一时（情境性和关系性）因素的影响。

**** 亲密恐吓：
两种目的：
+防止伴侣的离开
+反社会或相当自恋

亲密攻击能代代相传

*** 暴力的根本原因
进行亲密恐吓的男性似乎赞成雄性标志，凭此提升他对女性的权威，
但他们之中许多人对此任务却又感到能力不足。

*** 受害者不离开的原因
+间歇的暴力
+离开的代价很高
+害怕发生更为严重的暴力
+不想离开--具有高忧虑被弃的女性容易被占有和控制欲强的男性所吸引

* 亲密关系的解体与消亡
** 离婚率的变化
*** 离婚的普遍性
美国最近的婚姻最终以分居或离婚告终的可能性仍然接近50%。

*** 离婚率增加的原因
离婚的因素，而不一定是造成离婚的原因：
+我们渴望从婚姻中得到更多，对婚姻持有更高的期望标准
+上班的女性在经济上更为自由，有更多的机会接近有吸引力的替代伴侣，在工作和家庭之间面临的冲突日益严峻
+兴起的个人主义和社会流动性使我们与阻扼离婚的社区规范联系更少
+较低的性别比率
+新制定的法律使得离婚更为大众接受，离婚的程序也更为容易
+随意的同居削减了婚姻的忠诚
+离婚家庭的孩子长大后更容易离婚

** 离婚的征兆
*** 障碍模型
影响关系破裂的三类因素：
+吸引力
+替代选择
+使得个体很难逃脱亲密关系的许多障碍

莱文杰的模型有助于提醒我们离婚的障碍物会萦绕我们心头，
但该模型没有完全认识到，一点呐婚姻的不幸开始并延续，这些障碍物是多么无效。

*** 脆弱-应激-适应模型
该模型认为我们婚姻的质量取决于我们是谁（脆弱），我们遭逢的环境（应激）和我们应对环境的方式（适应）三者的相互作用，
并且在某种程度上这三个重要的因素还会彼此影响。

*** 亲密关系适应过程项目结果
浪漫爱情变化的规模和速度能最好地预测夫妻是否会离婚。

夫妻带入婚姻的问题决定了发生离婚的快慢。

*** 婚姻早期岁月项目结果
夫妻们构筑亲密关系的社会背景对他们的婚姻结果有重大的影响。
不管伴侣们是多么尊重和珍视婚姻，
贫穷和教育缺乏可能把任何夫妻都置于离婚的风险之中。

*** 个体对自己婚姻问题的知觉
当伴侣们对婚姻不满时，他们常常抱怨伴侣关系中的个别特点。
但更广泛的影响因素也很重要。

*** 特定的离婚信号
一般趋势的结论有时可能掩盖了某些重要的限制条件：
没有一个概况化的结果适用于每个婚姻，某些预测信号可能适用于某些团体或婚姻的某些阶段，
但却不适合其他情况。

** 分手
*** 与婚前伴侣的分手
两个重要区别：
+直接的还是间接的分手策略
+个体的分手的努力是指向他人（设法保护伴侣的情感）还是指向自己（在损害伴侣情感情况下自私自利）

*** 离婚的阶段
+单人阶段：伴侣一方变得不满意，经常感到沮丧和不悦
+双人阶段：不幸福的伴侣表露出他们的不满，接着出现协商、对峙或者尝试顺应
+社交阶段：伴侣们公开宣扬他们的苦恼，向家人和朋友解释他们的遭遇，并寻求支持和理解
+善后阶段：重新通过认知加工克服他们的失败，并丢弃过去的伴侣关系
+复兴阶段：已离婚的伴侣作为单身进入社交生活，常常告诉别人他们的经验使他们更加聪明睿智

** 分手的结果
*** 解体后的关系
大多数情况下，未婚的伴侣在决定分手后，随着时间的推移彼此联系会越来越少。

*** 克服消极情绪
虽然分手常常看起来非常可怕，但分手对我们的伤害并没有我们想象的那么严重。

沉溺于失去的恋情延长了我们的苦恼，
而反省--找寻我们经历中的意义并希望从中得到学习提高，
是与正面适应和恢复联系在一起的。

*** 离婚不同于恋人分手
**** 适应
整体来看离婚是困难的跋涉过程，人们在离婚后的岁月里并不太顺利，
但耗费了数年之后，大多数人都能逐渐恢复到从前。

我们还得承认丧偶之人所承受的毁灭性的丧亲之痛。
这种损害的程度是局外人很难理解的。

**** 社交圈子
人们在离婚后的数年时间里社交圈子一般变得更小了。

**** 经济资源
平均而言，离婚后女性的生活标准下降了，而男性则提高了。

**** 前配偶之间的关系
四种类型的婚后关系：
+暴躁的仇敌
+愤怒的伙伴
+合作的同事
+完美的朋友

*** 父母离异的孩子
父母离异的整体影响始终是负面的，但程度相对适中。

如果子女能享受到免于贫困的自由，得到慈爱、可靠和持续的养育，
免受双亲冲突的戕害，他们就能幸福地成长。

* 亲密关系的维持和修复
** 亲密关系的维持和提升
*** 保持忠诚
**** 认知维持机制
+认知上的相互依赖：他们不再把自己视为单独的个体，而是视为包括他们和伴侣在内的更大整体的一部分
+积极错觉：彼此理想化并尽可能以最好的眼光来看待他们的亲密关系
+认知到的优越
+对替代选择的无视：满足的伴侣意识不到替代关系中可能得到的好处
+贬低诱人的替代选择

**** 行为维持机制
+牺牲的意愿
+米开朗其罗现象：当伴侣鼓励我们成为自己所期望的人时，我们的亲密关系和个人幸福都会得到提升
+顺应现象
+容易实行的行为维持机制-玩乐
+那些忠于伴侣关系的人在伴侣背叛之后更有可能宽恕对方

**** 亲密关系的秘诀
+欣赏你的伴侣
+表达你的感激
+重复上述两部

*** 保持满足
能最好地预测幸福婚姻的是积极性、保证和分担任务。

这些维持机制的时间是短暂的：
如果这些理想的活动停下来，满足马上会开始下降。

** 修复关系
*** 自我实践
*** 预防性维持
*** 婚姻治疗
职业咨询师采用的治疗方法多种多样，有三种不同的治疗方法：
+行为的方法
+情绪中心的治疗
+顿悟导向的治疗

选择最吸引你的治疗和治疗师。
