* 人际关系的构成
** 亲密关系的性质和重要性
*** 亲密关系的性质
+ 了解程度
+ 关心程度
+ 相互依赖性：彼此需要的程度和影响对方的程度（特征：频繁、强烈、多样和持久）
+ 相互一致性：自我接纳他人的程度是测量一致性最生动、直接的方法。
+ 信任度
+ 忠诚度

*** 归属的需要
归属是人类长期演化的产物。

如果我们要正常地生活和保持身心健康，就需要在长久、关爱的亲密关系中经常与伴侣愉快地交往。

** 文化的影响
文化标准是人们建立人际关系的基石，它影响着人际关系的期望，限定了正常的人际关系模式。

*** 亲密关系变化的根源
影响人际关系规范更重要的因素是特定文化下青年男女的相对数量-性别比率。

原因可能是：社会规范的演变总是满足那些掌握经济、政治和法律权力的强势人群的利益。

** 个人经历的影响
依恋类型：安全型、痴迷型、疏离型和恐惧型。

个人经验在塑造人际关系的依恋类型上有着重要的作用。

尽管依恋类型能够改变，但他们一旦确定后，既稳定又持久，并影响着人们建立新的人际关系，加强已有的行为倾向。

** 个体差异的影响
*** 性别差异
+ 有些两性的差异的确存在，但非常小。
+ 男人或女人性别内的行为和观点差异远大于两性之间的平均差异。

*** 性认同差异
性认同差异指的是由文化和教育引起的两性在社会性和心理上的差异，或者叫社会性别。

把与任务有关的“男子气”的才能称为工具性特质，
把与社交和情感有关的“女人味”的技能称为表达性特质。

正是这些差异“实际上造成了很多不和谐”，最终导致人际关系的失败。

*** 人格
人格特质较稳定，长期也只会缓慢地变化。

最终要的人格特质可能是那个有消极作用的特质：神经质。

*** 自尊
对自我的评价构成了自尊。

社会测量学具有启发性的主导理论认为，自尊是人们的主观计量器，即“社会关系测量学”，测量我们与他人人际关系的质量。

低自尊的人有时低估伴侣对他们的爱，从而损害亲密关系，还觉知到根本就不存在的伴侣的漠视。

** 人类本性的影响
演化学的三个基本假设：
+ 性选择使人类成为今天的物种。
+ 两性之间之所以存有差异，只是因为某种程度上他们在过去面临着不同的繁殖困境。
+ 文化影响决定了演化形成的行为模式是否具有适应性-并且文化的变化比演化快的多。

演化学原理认为：任何普遍的心理机制之所以以它目前的形式存在，是因为它一直在帮助人类解决过去的生存或繁殖问题。

通过识别人类共有的行为模式来描绘人类的本性，是演化学视角最令人信服的研究领域之一。

** 人际互动的影响

** 人际关系的消极面

* 研究方法
探讨某个特定研究课题的方法很多，各有其利弊。
真正的科学家会系统而认真地收集和评价各种信息，但没有任何一个单一的研究方法能得出绝对明确的答案。
** 问题的提出
亲密关系所涉及的问题来自所有这些根源：
科学家把他们自己的个人观察、他们对社会问题的认识、他们对前人研究的了解以及
他们自己的理论视角结合在一起去挖掘要回答的问题。

问题的分类:
+ 对某些事件或一系列事件的自然发生过程进行描述。
+ 确定事件之间的因果关系，以确定哪些事件对随后的结果有显著的影响，哪些没有。

不同的研究有不同的目的。如果某项探索性实验是为了描述新发现的现象，我们不应该因为它确定不了因果联系而去苛责。

不要试图从以描述为目的的研究中得出因果联系。

** 被试的选取
+ 方便取样
+ 代表性取样：确保被试与研究的整个总体之间的相似性。

不过人际关系的研究者所考察的许多过程非常基础，在人口统计学上不同的人群间在此方面并不存在过大的差异。

** 研究的设计
*** 相关设计
相关的存在意味着可能有很多不同的似是而非的因果关联。

运用高级统计技术却有可能在相关设计的结果上得出一些因果联系的可靠结论。

*** 实验设计
实验提供了原因和结果的最直接了当的结论，因为实验者创造并控制了他们研究的条件。

在真实验中，研究者有意操作一个或多个变量，并把被试随机分配到这些事先创造的不同条件下，
从而观察这些条件变化怎么影响人们的行为。

*** 发展性研究设计
发展性研究设计研究行为或事件随时间而改变的方式。

**** 横断研究设计
比较处在不同人生阶段或者不同年龄者的发展过程。

某些不确定性的影响：所经历的不同社会、文化和政治事件。

**** 纵向研究设计
对同一人群在一段时间内反复进行测量。

不确定性的影响：
+ 社会文化的巨大变化仍然会混淆年龄和经验的影响。
+ 被试流失。

**** 回朔研究设计
在时间上往回走。

不确定性的影响：记忆和认知偏差。

** 场景的选择
实验室和自然场景的优缺点恰好互补。

*** 实验室
**** 优点
+ 能有效控制外在的、无关变量的影响。
+ 能精确控制被试要经历的体验，还能安排符合研究目的的物质环境

**** 缺点
可能引发被试的虚假行为，使我们对他们的认识不足。

*** 自然场景
**** 优点
被试在日常的环境中感到舒适和放松，从而使实验者可能引发而获得更多的典型行为。

**** 缺点
自然场景可能充满了与研究问题无关的干扰变量。

** 数据的性质
无论我们采用何种数据，对行为的测量应该同时具备心理测量学上的效度（我们测量到的事件是我们真正试图测量的）和
信度（如果这些事件不会发生变化，我们在不同时间的测量结果应该一样）。

*** 自我报告
自我报告有着重要的价值：
+ 能告诉我们人际关系事件对当事人的意义。

**** 潜在的问题
+ 被试对问题的解释
+ 回忆或觉知的困难
+ 被试报告的偏差（自我服务偏差，社会赞许性偏差）

*** 观察法
科学观察并不是轻松随意的工作。研究者要么采用复杂的工具测量行为，要么细心地训练助手以使观察尽量准确、可靠和详尽。

**** 观察方法
+ 直接观察正在发生的行为
+ 采用记录设备

**** 存在的问题
反应性问题：如果人们知道自己正在被观察就会改变自己的行为。

*** 生理测量
如果我们观察的行为是人们无法有意识地加以控制的，就可以避免反应性问题发生。
对人体自主的和生化的反应进行生理测量就能做到这一点。

生理测量一般成本较高，但其应用在不断增加，因为生理测量能让研究者考察我们行为的生理根源和社会根源之间的重要关系。

*** 档案材料

*** 夫妇报告
夫妇任何一方都要报告自己的行为，同时也是伴侣行为的观察者。

** 研究应遵循的道德规范
科学在道义上必须履行的责任是求得真知造福人类。

** 结果的解释和整合
如果心理学、社会学或传播学研究的结果具有统计学上的显著性，这表明这种结果不太可能随即发生，但不是完全不可能随即发生。

像科学家那样思考：
没有一项研究是完美无缺的，但真理就在前方。我们更相信不同的科学家采用不同的被试样本研究得出的结果。
如果研究结果用不同的方法得到重发，我们就更有信心。

元分析：
研究者把针对某一特定现象的所有现存研究汇编到一起，分析整合它们的结果以识别它们的共同规律。

* 吸引力
** 吸引力的基础：一种奖赏
人与人之间产生吸引力最基本的假设是：
他人的出现对于我们有奖赏意义。

影响吸引力的奖赏有两种类型：
与他人交往产生的直接奖赏，和仅与他人有关的间接利益。

** 临近：喜欢身边的人
*** 方便：远亲不如近邻
如果他人在我们身边，我们很容易得到他们提供的各种奖赏。

*** 熟识：重复接触
曝光效应：
刺激的简单暴露能够提高个体的态度体验，人们对他人或事物的态度随着接触次数的增加而变得更积极的一种现象。

*** 临近的作用
临近能增强我们对他人的情感。如果我们与他人相处愉快，当他们在身边时我们会更喜欢他们。
然而，如果我们讨厌某人，临近只会使事情变得更糟糕。

** 长相吸引力：喜欢那些可爱的人
*** 吸引力的刻板印象
外貌吸引力的刻板印象普遍存在，但俊美之人有哪些优势，一定程度上取决于具体文化所强调的价值观。
但也容易被认为较放荡。

*** 吸引力的秘密
对是否美丽所判断的一致性要远大于分歧性。并且这种共识是跨种族的。

面孔：对称和“平均”

身材：腰臀比

*** 长期吸引力的演化观

*** 文化也起作用
人类本性和环境条件一起塑造了我们对美丑的共同判断标准。
我们常常被那些看起来是个好配偶的人所吸引，但具备什么样的条件才算是好配偶，一定程度上依赖于我们所居住的环境。

*** 对美丽持有偏见的人
在全世界，男性比女性更为关注恋人的长相吸引力。

高自我监控（人们为适应不同的情境而调控自己行为的能力）的男性特别关注恋爱伴侣的俊美长相。

*** 美丽：交织着的代价与收益
女人的美貌和她与男人交往的时间整体上看并无相关。

男人的长相和他们与女人交往的次数和时间存在相关。

俊美之人常常能与别人愉快的交往，但不如长相平庸的人那样信任别人。

*** 长相吸引力的匹配
亲密关系越正规严肃、投入程度越多时，匹配程度就越明显。

** 礼尚往来：喜欢那些喜欢我们的人
对未来伴侣的期望值=伴侣的长相吸引力×伴侣接纳自己的可能性

我们期望伴侣接纳自己的可能性大小，很大程度上和自己的适配价值即作为生殖伙伴的综合吸引力有关。

喜欢那些喜欢我们的人不仅符合吸引力的奖赏模型，还符合平衡理论：人们期望他们的思想、感情和社交关系能够保持一致。

** 相似性：喜欢与我们相像的人
人际关系最基本的原则之一就是相像律：相类似的人彼此吸引对方。

有吸引力的相像种类体现在各个方面，共同点越多，彼此越喜欢。

匹配是广泛的过程，有时人们是在用一种优势交换伴侣的另一种优势，但双方却有着类似的适配价值。

知觉到的相像程度和婚姻满意度之间的相关高于真实的相像和婚姻幸福之间的相关。

某些相像比其他相像更重要。

差异可能随着时间而减少。

我们喜欢那些与我们理想自我相像的人。

互补性存在于伴侣双方的不同行为：支配与顺从。

*** 亲密关系的三个不同阶段
刺激-价值观-角色

时间和经验的影响还表现在致命的吸引：如果伴侣最初吸引人的品质逐渐变成最惹人厌烦、烦恼的特点，致命的吸引就产生了。

*** 相像具有吸引力的原因
提醒我们这样是没有问题的。

** 障碍：得不到的就喜欢
罗密欧与朱丽叶效应：父母越是干涉子女的恋爱自由，他们彼此之间就越会相爱。

打烊效应：得不到的禁果格外甜。

** 男女两性的理想伴侣
+ 热情和忠诚
+ 吸引力和活力
+ 社会地位和资源

*** 性别差异
男人往往确保女友有普通的长相，
女人往往确保男友有点金钱和前途。

* 社会认知
** 第一印象
** 知觉的力量
** 印象管理
*** 印象管理策略
*** 亲密关系中的印象管理
** 我们了解伴侣的程度

* 沟通
** 非语言沟通
*** 非语言沟通的组成
*** 非语言沟通的敏感性
*** 非语言沟通中的性别差异
** 言语沟通
*** 自我表露
*** 言语沟通中的性别差异
** 沟通障碍及其应对
*** 沟通不良
*** 精确表述
*** 积极倾听
*** 守礼而镇定
*** 尊重和确认的力量

* 相互依赖
** 社会交换
** 亲密关系的经济论
*** 与时俱变的奖赏和代价
** 亲密关系中的贪婪
*** 相互依赖的实质
*** 交换关系和共有关系
*** 公平关系
*** 小结
** 忠诚的本质
*** 忠诚引起的后果

* 友谊
** 友谊的本质
*** 友谊的属性
*** 友谊的规则
** 友谊的毕生变化
** 友谊的差异
*** 友谊的性别差异
*** 友谊的个体差异
** 友谊发展的障碍
*** 羞怯
*** 孤独

* 爱情
** 爱情简史
** 爱情类型
*** 爱情三角理论
*** 浪漫狂热之爱
*** 相伴之爱
*** 爱恋风格
** 爱情的个体差异
*** 依恋类型
*** 年龄
*** 性别
** 爱情很难持续
*** 浪漫爱情难以持久的原因
*** 爱情的未来

* 性爱
** 性态度
*** 对随意性行为的态度
*** 对同性恋的态度
*** 性态度上的文化差异
** 性行为
*** 第一次性行为
*** 忠诚关系中的性行为
*** 不贞
*** 性欲望
*** 安全明智的性行为
** 性满足
*** 性沟通
*** 性满足与关系满意度
** 性胁迫
