* 什么是全局路径规划
** 全局路径规划的任务
为无人艇完成任务而设计路径的系统。

** 全局路径规划的目的和意义
在无人艇实际运行之前，提供一个路径给导航算法进行跟随。

** 全局路径规划的一般步骤
+ 建立环境信息地图
+ 在地图上确定所需要经过的一系列航途基准点
+ 在航途基准点的基础上生成一条优化的路径

** 所需要考虑的一些因素
+ 无人艇的动力学因素
+ 安全无碰的要求
+ 路径生成中的假设：为了不产生不希望的效果，生成的路径能够满足速度连续和通过位点这两个要求

** 全局路径规划和局部路径规划的区别
全局路径规划在障碍物信息已知的整个构型空间中应用，最终找到一条从当前点到终止点的无碰撞路径。

而局部路径规划只考虑无人艇周围一定范围的环境，并且可以利用避碰算法对周边的障碍物做出反应。

* 全局路径规划研究现状

** 国内研究现状

** 国外研究进展

* 全局路径规划算法介绍

** 根据步骤分类

*** 建立环境地图

环境地图可以分为定性的和定量的两种。

**** 定性地图

定性的地图也叫做拓扑图，它只考虑节点及其各个点之间的可达性这类拓扑关系，
而忽略了节点之间的几何关系。
定性的地图由于只有节点之间的定性的描述，所以只能规划出可行路径。

定性的地图除了在只需要规划出可行路径的任务中使用之外，
也可以在一些复杂任务中和定量地图结合使用，
比如区域分割算法中，分割后的区域就被构建成一个拓扑图。

**** 定量地图

定量地图也被称为度量地图。
度量地图一般在地图的构建中考虑了原始数据中的位置距离信息。
因此定量地图中是可以依据某些测量指标规划出极值路径。

定量地图有下面这几种常用的类型：
+ Meadow地图：将自由空间划分为凸多边形，再使用凸多边形的中点进行规划。
+ Voronoi图：生成到最近的两条边都等距的线作为最后规划的路径的集合。
+ 均分栅格
+ 四叉树地图：一种为了节省内存空间的递归栅格结构。
当且仅当栅格中有障碍物，但又没有被障碍物完全占据时，
递归划分栅格。

*** 规划出无人艇的航途基准点

规划无人艇的航途基准点的算法是全局路径规划的关键，
也是被大量研究的。
规划航途基准点的算法除了经典的搜索方法，还有新式的基于采样的路径规划方法，
以及新颖的RRT算法。
除此之外，还有适用于特殊类型任务的路径覆盖规划算法。

*** 在航途基准点的基础上生成一条优化的路径

对上面规划出的航途基准点，可以直接用直线相连，作为最终路径返回。
这种方法虽然简单，但是对于需求高精度的任务来说却是不够的。

基本的路径优化方法有考虑了起始点，终止点和最大转弯半径的Dubins方法。
其他较为流行的还有Pythagorean Hodographs。

** 根据任务类型分类

*** 通用型的起始点终止点路径规划的任务

路径规划中被研究最多的一类问题就是从起始点到终止点的路径规划问题。
这类问题的几大解法也均被广泛研究，它们的优缺点以及相应的改进方法也都被有大量的文献提及。

这类问题的解法主要但却不限于如下几种：
+ 基于搜索方法的Dijkstra,A*以及相应的变种
+ 人工势场的方法
+ 基于控制的方法

*** 和特殊需求相关的任务

当前全局路径规划模块所完成的矩形区域扫测任务、圆形区域巡逻任务都是和经典的起始点终止点路径规划问题相区别的任务。
这些问题的解决可以通过将指定任务转换为被广泛研究的起始点终止点路径任务的问题，
比如圆形区域巡逻任务就是采用的这样的解法。
或者重新定义出一种值得研究的问题，
比如矩形区域扫测任务与扫地机器人完成清洁任务的任务类似都可被定义为一种路径覆盖规划(Coverage Path Planning)的问题，
路径覆盖规划问题的有如下常用的算法。

**** 经典的精确分割方法(classic exact celluar decomposition methods)
均为离线算法--依赖的是静态信息，并且假设环境信息已知，其中的障碍物均为多边形障碍物。

**** 四边形分解(Trapezoidal decomposition)
分解后的区域均为四边形，不过仅处理平面的多边形空间。分解之后的区域通过简单来回动作即可实现区域的完全遍历。

**** 左行右行交互式分解(Boustrophedon decomposition)
因为四边形分解法只能产生四边形栅格，其产生的很多栅格即使合并在一起也是可以完成全路径的覆盖的。

该种分解方法和四边形分解法类似，不过它仅仅考虑垂线段上可以同时延伸到点的上方和下方的点。

**** Morsed-based celluar decomposition
***** 基本方法
该种方法是Morse函数的关键节点以及基于起点和终点的路线图(roadmap)的方法。

通过使用感觉范围的信息来探测关键点，
使用基于运动模板的算法(motion-template-based)算法来确保探测到在目标区域中的所有关键节点。

***** 优点
+ 相对于经典的区域分割方法，Morse-based分割可以处理非多边形的障碍物。
+ 通过选择不同的Morse函数来确定切片的形状，可以产生不同的分解和路径覆盖模式，
对于有运动约束的载体来说是特别有效的。
+ 理论上，这种方法可以适用于任何维度的空间。
+ 这种方法也适用于在线的完全覆盖任务

***** 缺点
Morse分解应用于直线运动的环境，因为此时相对应的拓扑环境会发生改变，
关键点会无法探测到。

**** 神经网络的方法
Luo和Yang将栅格地图划分为栅格大小等于机器人的覆盖半径的情况下，
再利用基于membrane方程的shunting方程来决定与栅格对应的每个神经元的动力值。

***** 优势
可以处理动态环境

***** 改进
Qiu添加了局部路径规划的技术来减少计算量。

一个在有限时间内对机器人实行连续控制的相关方法也被提出。

***** 区域扫测任务

** 根据算法的原理分类

*** 几何算法
**** 可视图法
可视图一般是用来表示一系列点和障碍物之间的可视位置关系的图。
图中每个点表示一个点的位置，每一条边表示它们之间的可视连接。

***** 基本方法
加入了障碍物的顶点和工作区域顶点之后，连接可视的边。
下面两种情况的连线可认为是可视边：
+ 连线对应于障碍物上的边
+ 连线存在于自由空间中

***** 优点
可以解决多边形障碍物的情况。

***** 缺点
+ 可视图法需要将每个障碍物相连，会产生N^2条边，极大的占用了存储空间。
不过已经有一些改进方案比如：Reduced Visibility graphs。
+ 我们需要加入起始点和终止点以及对应的每一条边。

*** 势场法
经典的势场法通过计算一个来自终点的吸引力和来自所有障碍物的排斥力的和，
以在工作空间的每个点生成一个向量。
之后可以通过梯度下降的方法来引导机器人到达终止点。

*** 基于栅格的搜索方法
基于栅格的方法是在构型空间中覆盖了一层栅格，其假设每个栅格点的构型都是不同的。
其通过栅格精度来调节计算速度和路径的完备性。

**** 基本方法
在每个栅格中都可以移动到相邻的栅格点只要不会发生障碍物的碰撞。
可以结合图论的搜索方法来找到一条从起点到终点的最优路径。

**** 一些改进方案
+ 传统的基于栅格的方法产生的路径被限定在几个固定的方向，通常会导致只能获得次优路径。
Any-angle path planning通过栅格的边上传递信息来获取最短路径。

*** 基于采样的路径规划方法
**** 优点
+ 和别的路径规划方法相比，只需要一个很小的存储空间
+ 适用于有差分约束的系统
+ 适用于有很多自由度的系统
+ 在包含了数量很多并且非常复杂的状态空间中可以快速生成一条可行路径
+ 大部分基于采样的方法是概率完备的
（如果路径存在并且不断增加采样个数，找到路径的概率就会收敛到1）

**** 缺点
+ 不具有最优性和完备性(no optimality or completeness?)。
和方案质量与运行时间之间的权衡。
+ 在窄通道和约束表面附近的很难生成采样点

**** 概率地图法(Probabilistic Roadmap)
在状态空间中使用了随机采样的方法来构建了一个由自由状态空间组成的地图。

***** 基本步骤
+ 在状态空间中均匀地随即生成采样点（有多种不同效果的采样策略）
+ 通过检查是否碰撞来获取无碰撞的采样点
+ 通过使用可以寻找最近的无碰撞的路径的局部规划器来将每个采样点和最近的k个采样点相连。
+ 最后在地图中进行图论搜索来寻找到一条最短路径。

** 根据运动学模型分类

*** 简单的模型

无人艇路径规划中关于艇的运动学模型的最简单的假设就是：
在平面上可以不管当前艇的朝向从一个点移动到任意一个点。

该假设对无人艇运动及算法的约束是非常弱的，在该假设下上述的各个算法均可以使用。

*** 考虑无人艇的动力学因素

因为实际无人艇的转角范围是有限制的，所以上述的运动约束并不适用。
而且无人艇的实际转角应该是连续的而不应该产生突变。

**** 无人艇的转角约束

无人艇的转角约束一般会在基本路径规划算法的基础上进行改进，
比如对基本的A*算法加上转角限制。

**** 无人艇的转角连续化

为了使无人艇的转角连续化，
常用的策略是在使用路径规划算法生成航途基准点后，
对路径优化方法进行优化。

*** 考虑海浪的干扰影响

无人艇在海洋中的实际运行中，海浪对无人艇运动的不确定性的影响是非常大的，
而且不同等级的海浪产生的影响也是不同的，
所以在全局路径规划考虑无人艇和障碍物的碰撞时，
加入海浪的干扰也是非常必要的。

在考虑海浪干扰的路径规划中，
目前提出的方法有马尔可夫状态决定过程和结合了A*算法和博弈树的look-ahead算法。
