* 知觉、记忆和情境
不依赖于情境的决策是不存在的。
我们所做出的决策与判断都取决于我们看待和解释世界的方式。

** 选择性知觉
知觉的本质就是具有选择性的，在很大程度上取决于认知和动机因素。

人们的知觉受到了已有信念和预期的强烈影响，这些被称为“认知”因素。
那些与希望、欲望以及情感等因素相关的影响被称为“动机”因素。

在我们做出重大决策之前，我们可以思考下面问题：
+我看待事物的方式是否受到了某种动机的驱使？
+我在看待和处理问题时是否夹杂着自身的预期？
+我是否与那些和我有着不同预期和动机的人交换过意见？

** 认知不协调
为了保持一致性，人们常常不得不去改变他们的信念使之与行为一致。

*** 自我知觉理论：
+ 人们对自己的态度、情绪以及其他一些内在状态的认知和发现，部分是通过观察自己在各种情况下的行为来实现的。
+ 由于内部线索微弱、模糊和难以解释，人们的自我认知就与外部观察一样，需要推断得出。

*** 自我知觉理论和认知不协调的差别：
+ 自我知觉理论是从人们如何推断行为原因的角度来解释实验结果。
+ 认知不协调理论是从人们天生所具有的减少内部冲突或不协调状态的动机的角度来解释实验结果。

*** 应用
+ 人们为一件事付出越多，就越认为这件事有价值，而且越有压力为这件事情继续付出。
+ 登门槛效应

** 记忆和事后聪明式偏差
记忆是在我们提取它的时候才建立起来的，
在发生重建的时候，我们所用到的重建材料也就是那些填补缺失细节的逻辑推断、与原始记忆混合在一起的关联记忆以及其他一些相关信息。

除了做好仔细的记录并保管好有关过去事件的记录外，再没有其他什么更好的方法能够避免出现这些记忆偏差了。

*** 事后聪明式偏差
将已经发生的事情视为相对不可避免和显而易见的事情，
却忽略了自己的判断实际上已经受到已知结果的影响。

*** 减少事后聪明式偏差
如果人们开始考虑有哪些因素可能导致实验出现不同结果，事后聪明式偏差就消失了。

** 情境依赖性
决策者不是孤立地去感知和记忆某个事件，而是根据他们过去的经验和事件发生时的情境去理解和解释新信息。
在不同情况下，同一个人对同一刺激的认知可能会完全不同。

虽然情境效应的作用不是无限的，但人们通常低估了日常生活中的情境效应。

*** 对比效应
只有当对比的刺激物彼此类似时，对比效应才存在。

*** 初始效应
初始效应是有关进入位置及其对判断的影响的一个总体描述。
也就是说，第一印象固然是重要的，第二和第三印象也同样显示出很大的初始效应。

*** 近因效应
在一些情况下，最后出现的信息会比最先出现的信息的影响更大。

近因效应是由记忆的差别引起的：
+ 如果人们连续列出有利原因和不利原因，就会出现很强的初始效应。
+ 如果人们在列出有利原因和不利原因之间有3分钟的间隔，就会出现近因效应。

*** 晕轮效应
+ 长相美丽的晕轮效应。
+ 在描述中引入一个中心特征，如热心或者冷漠，能够影响被试对这个人的整体印象。

* 问题如何影响答案
** 可塑性
问题的语境和措辞对决策与判断具有影响。

*** 顺序效应
人们的答案也可能受到问题或者选项顺序的影响。
这些影响通常很小，但在某些情况下，其影响却可能变得非常深远。
比如说，如果两个问题都是同一主题，而且回答者需要表现得一致，
那么回答者就会照着前一个问题的答案的思路来组织后一个问题的答案。

顺序效应中最常见的是近因效应，也就是说，
当某一答案选项出现在备选答案的最后时，其被选择的频率更高。

*** 虚假意见
如果人们对一个问题一无所知，一部分人会表现出完全可塑性;
在某些特别的询问方式下，一部分人会对这一问题发表意见，但实际上他对此并不真正了解。
这种看法被称为“虚假意见”。

** 问题的措辞和框架的影响
* 决策模型
** 期望效用理论
** 理性决策的悖论
** 描述性决策模型
* 直觉与偏差
** 代表性直觉
** 易得性直觉
** 概率和风险
** 锚定与调整
** 对随机性的知觉
** 相关性、因果性与控制
** 归因理论
* 决策与判断中的社会性一面
** 社会影响
** 群体决策与判断
* 常见陷阱
** 过度自信
** 自我实现的预言
** 行为陷阱
