* 知觉、记忆和情境
不依赖于情境的决策是不存在的。
我们所做出的决策与判断都取决于我们看待和解释世界的方式。

** 选择性知觉
知觉的本质就是具有选择性的，在很大程度上取决于认知和动机因素。

人们的知觉受到了已有信念和预期的强烈影响，这些被称为“认知”因素。
那些与希望、欲望以及情感等因素相关的影响被称为“动机”因素。

在我们做出重大决策之前，我们可以思考下面问题：
+我看待事物的方式是否受到了某种动机的驱使？
+我在看待和处理问题时是否夹杂着自身的预期？
+我是否与那些和我有着不同预期和动机的人交换过意见？

** 认知不协调
为了保持一致性，人们常常不得不去改变他们的信念使之与行为一致。

*** 自我知觉理论：
+ 人们对自己的态度、情绪以及其他一些内在状态的认知和发现，部分是通过观察自己在各种情况下的行为来实现的。
+ 由于内部线索微弱、模糊和难以解释，人们的自我认知就与外部观察一样，需要推断得出。

*** 自我知觉理论和认知不协调的差别：
+ 自我知觉理论是从人们如何推断行为原因的角度来解释实验结果。
+ 认知不协调理论是从人们天生所具有的减少内部冲突或不协调状态的动机的角度来解释实验结果。

*** 应用
+ 人们为一件事付出越多，就越认为这件事有价值，而且越有压力为这件事情继续付出。
+ 登门槛效应

** 记忆和事后聪明式偏差
记忆是在我们提取它的时候才建立起来的，
在发生重建的时候，我们所用到的重建材料也就是那些填补缺失细节的逻辑推断、与原始记忆混合在一起的关联记忆以及其他一些相关信息。

除了做好仔细的记录并保管好有关过去事件的记录外，再没有其他什么更好的方法能够避免出现这些记忆偏差了。

*** 事后聪明式偏差
将已经发生的事情视为相对不可避免和显而易见的事情，
却忽略了自己的判断实际上已经受到已知结果的影响。

*** 减少事后聪明式偏差
如果人们开始考虑有哪些因素可能导致实验出现不同结果，事后聪明式偏差就消失了。

** 情境依赖性
决策者不是孤立地去感知和记忆某个事件，而是根据他们过去的经验和事件发生时的情境去理解和解释新信息。
在不同情况下，同一个人对同一刺激的认知可能会完全不同。

虽然情境效应的作用不是无限的，但人们通常低估了日常生活中的情境效应。

*** 对比效应
只有当对比的刺激物彼此类似时，对比效应才存在。

*** 初始效应
初始效应是有关进入位置及其对判断的影响的一个总体描述。
也就是说，第一印象固然是重要的，第二和第三印象也同样显示出很大的初始效应。

*** 近因效应
在一些情况下，最后出现的信息会比最先出现的信息的影响更大。

近因效应是由记忆的差别引起的：
+ 如果人们连续列出有利原因和不利原因，就会出现很强的初始效应。
+ 如果人们在列出有利原因和不利原因之间有3分钟的间隔，就会出现近因效应。

*** 晕轮效应
+ 长相美丽的晕轮效应。
+ 在描述中引入一个中心特征，如热心或者冷漠，能够影响被试对这个人的整体印象。

* 问题如何影响答案
** 可塑性
问题的语境和措辞对决策与判断具有影响。

*** 顺序效应
人们的答案也可能受到问题或者选项顺序的影响。
这些影响通常很小，但在某些情况下，其影响却可能变得非常深远。
比如说，如果两个问题都是同一主题，而且回答者需要表现得一致，
那么回答者就会照着前一个问题的答案的思路来组织后一个问题的答案。

顺序效应中最常见的是近因效应，也就是说，
当某一答案选项出现在备选答案的最后时，其被选择的频率更高。

*** 虚假意见
如果人们对一个问题一无所知，一部分人会表现出完全可塑性;
在某些特别的询问方式下，一部分人会对这一问题发表意见，但实际上他对此并不真正了解。
这种看法被称为“虚假意见”。

** 问题的措辞和框架的影响
*** 开放性问题
量表不仅仅是被试用来描述他们行为的“衡量工具”。
更确切的说，被试在评价他们自身的行为时，往往利用了答案选项所提供的行为范围作为参照框架。

*** 社会称许性
当人们对一个问题并没有很坚定的信念时，
他们通常会对那些“最广为流传的句子”做为反应，
这些句子使得人们的态度往社会所赞许的方向靠拢。

*** 心理分账
决策者不仅会构架他们的选择-他们也会构架选择的后果。
+ 简单账户：某一结果是从动作直接结果的角度来描述的。
+ 综合账户：需要综合考虑这一动作与其他行为的先前关系。

*** 结论
对于那些有关决策与判断的调查和研究，
一定要考虑人们的答案是否会随着以下因素而发生变化：
+ 问题呈现的顺序
+ 问题出现的情境
+ 问题是开放式还是封闭式
+ 问题是否经过了过滤：中间选项或不知道
+ 问题是否包含了某些时髦词句
+ 答案选项的范围
+ 答案选项出现的顺序
+ 问题是从收益还是从损失的角度来提问的

由于判断往往容易受到问题措辞和框架的影响，
最安全的做法就是以多种方法来测试和比较结果。

* 决策模型
** 期望效用理论
*** 期望效用理论
+ 有序性
+ 占优性
+ 相消性
+ 可传递性
+ 连续性
+ 恒定性

*** 理论的扩展
+ 人们对某个事件可能发生的主观概率也纳入进来
+ 偏好的随机性

** 理性决策的悖论
我们并不知道人们犯错误的成本与人们遵循这些理性原则的成本相比，
哪个更大。

*** 阿莱悖论
相消性原则

*** 埃尔斯博格悖论
相消性原则

*** 不可传递性
*** 偏好逆转

** 描述性决策模型
*** 前景理论
+ 规避损失
+ 禀赋效应：当一件物品成为人们的禀赋时，其价值便增加了。
（损失的感觉比得到更加强烈）
+ 偏好取决于问题的框架：相对于参照点，
如果某项结果看起来是收益，决策者趋向于规避风险;
如果看起来是风险，决策者趋向于偏好风险。
+ 偏好是决策权重的一个函数，而这些权重并不总于概率相对应。
决策权重常常会强调小概率事件而忽视一般或者高概率事件。

*** 确定效应
由同一个因素引起的结果概率减小，
在结果最初就确定时产生的影响要大于在结果最初只是可能时的影响。

前景理论认为，由于决策中常常强调小概率，
因而这些小概率事件的重要性总被夸大。

*** 虚假确定效应
与确定效应类似，只不过这种确定只是一种表象而不是真相。

相同优惠额度的免费比折扣服务更有吸引力。

*** 后悔理论
前景理论的竞争理论

**** 反事实推理
在某些特定情况下，人们将决策质量的衡量建立在与其他不同决策的后果相比较的基础上。

**** 后悔理论的假设
很多人都经历过后悔和欣喜的感觉。

在不确定的情况下，他们会预期这些感觉并将其作为决策时要考虑的一个因素。

*** 多属性理论
当需要在不同标准中做出选择时，通常没有一个客观的最优化策略。
因而人们只需要与他们的目标和价值观保持一致，而不是追求客观最优化。

*** 非补偿性策略
人们在面临多个备选方案的复杂方案时通常采用非补偿性策略。
与补偿性策略相反，这些策略不允许不同标准间进行相互协调。

四个著名的非补偿性策略：
+ 关联原则
+ 析取原则
+ 词典式策略
+ 逐步淘汰法

*** 优先标准
在相等价值的方案中，选取具有更高优先标准的策略。

* 直觉与偏差
通常情况下，直觉可以得到一个令人相对较为满意的答案。
但是利用直觉进行判断的缺点是，在某些情况下，直觉判断可能导致一些系统性的偏差。

** 代表性直觉
*** 代表性直觉
人们通常会根据A在多大程度上可以代表B，
或者说是A在多大程度上与B相似来判断事件发生的可能性。

随着情境细节数量的增加，该情境发生的概率只会逐渐降低，
但是它的代表性和由此带来的外显的可能性却会上升。

*** 小数法则
人们从总体中抽取的随即样本相互之间是类似的，
与总体之间的接近程度比实际的统计抽样理论所预测的要高得多。

人们认为偶然事件具有自我修正的功能，
这样的偏差也是来自代表性直觉，
因为人们总是希望随即抽取的样本能够很好地代表总体。

*** 手热现象
*** 忽视基准线
*** 非回归性的预测
人们在进行预测时往往缺乏对信息来源的诊断，
结果可能造成”非回归性的预测“。

向平均数回归是统计中的一个现象，
即较高或者较低的分数往往会伴随着一些更加接近平均数的分数。

*** 一些提高决策和判断的技巧
+ 不要被很细节的情境所迷惑
+ 只要有可能，无论什么时候都应该注意基线值：
当一个事件是极少发生或者是非常普通的事件时，基线值显得尤为重要。
+ 记住偶然性并不具备自我修正的功能：
过去的事件是否会对将来的事件产生影响。
+ 不要错误地理解向平均数回归：
极端的成绩往往会跟随着一些更接近平均数的成绩。

** 易得性直觉
决策者通常会依据一些容易想起来的事例来判断一种类别出现的频次或者事件发生的概率。

尽管生动效应在某些情境下是可以产生作用的，
但是其适用范围和效力都存在一定的局限性。
同时，依据易得性直觉的一般原则，相对于平淡信息而言，
对事件的生动描述可以提高人们对其发生概率和频次的判断。

** 概率和风险
建议：
+ 保持正确的记录
+ 警惕如意算盘
+ 将复合事件分解为简单事件

*** 矛盾信息的困惑
先验概率：
在新信息到来之前，对一个事件发生概率的最佳估计。

*** 这样的事情绝对不会发生在我身上
在其它条件都相同的情况下，
个体认为正性结果发生的概率比负性结果要高。

*** 复合事件
连续事件：一个事件是由A和B两个事件同时发生而组成的。

非连续事件：如果复合事件是由事件A和事件B其中的一件发生组成的。

决策者在判断一个复合事件的发生概率时，更加倾向于锚定或者固着在其简单事件的发生概率上：
+ 人们通常会高估连续事件发生的概率。
+ 人们往往会低估非连续事件发生的概率。

*** 保守主义
一旦人们形成了对某一事件的概率判断，那么当呈现给他们新信息的时候，
他改变其原先判断的速度是比较慢的。

*** 对风险的直觉
正如现实情况一样，对风险的知觉通常是非常复杂的。
对于绝大多数人而言，风险不同于对某一事件不良结果的预期，它的含义更加丰富。

公众对风险的知觉有三个维度：
恐怖风险：知觉到缺乏控制感，恐惧，灾难性，不良后果以及利益与风险不相匹配。
未知的风险：无法预测的，无法了解的，新颖的，以及其所造成的伤害是延期的。
面对某个特定时个体的数量。

普通个体并不能很好地估计各种风险的大小，
他们对风险的总体知觉总是从“巨大灾难发生的可能性”以及“对下一代的威胁”角度来考虑，
而不是根据其发生的可能性。

*** 事故可以使我们更安全吗
在很多情境中，个体对于风险的知觉通常会受到其先前观点的很大影响。

** 锚定与调整
个体的判断是以一个初始值，或者说是“锚”为依据的，然后会进行并不充分的上下调整。

锚定效应是一个非常有效的现象，
效应的大小取决于锚和“锚前估计”（在呈现一个锚之前，个体的平均判断）之间差异的大小，
直到两者达到相近的水平。

*** 锚地效应的例子
原则就是：一些看起来不可能发生的事情是有可能发生的，
但是一个具体事件发生的概率要小得多。

只要有一个23人的团队，就有50%的可能性使其中两个人的生日同在不确定的某一天;
但是需要有50%的可能性使其中某人的生日在特定的某一天，需要的人数则是10倍以上。

*** 结论
+ 最有效的应对方法是针对某个极端锚定值，确定一个反方向的相等的锚定值。
+ 对最佳或者最差案例的讨论可能会引起不易察觉的锚定效应。
+ 在做出最后决策之前，考虑多个锚定值是必要的。

** 对随机性的知觉
+ 决策者倾向过分解释随机事件
+ 一个非特定事件发生重合的可能性远远大于一个特定事件发生重合的可能性。
+ 如果情境都是由独立事件组成，其结果相同，那么三到四次相同结果的发生并不是不寻常的，
决策者应该尽量避免将相同结果的短期重复看作是有意义的。

** 相关性、因果性与控制
+ 决策者不应该局限于正性的、已被确认的关系。在判断相关关系时，没有出现的事实往往是最为关键的。
+ 在判断一个关系是否存在之前，决策者应该问自己，他们的判断是基于观察还是期望。如果是前者，相关关系就有可能被低估;而如果是后者，相关关系就有可能被高估。
+ 决策者必须很好地识别相关关系和因果关系，两个存在因果关系的事件之间可能只存在很弱的相关。

** 归因理论
+ 减少基本归因误差的一种方法就是更加关注共同反应的信息
+ 另一种消除误差的方法是反问自己如果身处相同的环境，自己将如何行为。
+ 由于因果归因往往取决于事件发生当时最为突出的因素，因此寻找隐藏的因素也是相当重要的。

*** 变异框架分析
**** 三种解释行为原因的方式
+ 行为人：情境中的个体可能是行为产生的原因
+ 环境：情境中的某些固有特征可能是导致行为的原因
+ 时间：特定时刻的某些因素引起了行为

**** 三种不同的信息来源
+ 共同反应：在相同的情境中，其他人是否采取同样的行为反应
+ 独特性：其他的情境或者其他的刺激是否产生相同的行为
+ 一致性：同样的事情是否每时每刻都会发生

**** 缺乏共同反应
对共同反应信息缺乏利用是忽视基线水平的典型情况

一致性信息和独特性信息对因果归因的影响是共同反应信息的几倍。

**** 突出因素
相对而言，突出的、易得的、生动的信息能够产生更大的影响力。

*** 交换位置
视觉的观察角度对个体的因果归因会产生很大的影响。

*** 归因偏差
+ 行为人-观察者归因差异
+ 基本归因误差
+ 忽视基准线水平
+ 自我服务偏差
+ 正性偏差
+ 最终归因误差
+ 个体认为他人的多样性没有自己多

* 决策与判断中的社会性一面
** 社会影响
*** 社会易化
有观众在场会损害个体完成复杂任务的正确率，
同时对完成简单任务的正确率会稍有改善。

*** 社会性懈怠
当人们作为一个群体的一员做一件事情时，
就不会像自己独立完成时那么努力。

*** 旁观者干预
在相对较大的群体中，给予帮助的责任会被分散。
当人们面临着是否干预某件事的决策时，他人在场就会影响到他们如何决策。

*** 社会比较理论
人们具有评价自身能力水平和自身观点恰当性的需要。
那么在缺乏客观的、非社会性的标准时，人们就会把自己和其他人做比较。

*** 社会性痛觉丧失
社会比较既影响疼痛评价也影响躯体反应。

*** 从众
当情境中存在强大的从众压力时，单个异议者会起到较大的作用。

*** 少数派影响
只有在实验者同伴坚持同一个判断的情况下，少数人才会有显著影响。

*** 群体盲思
群体盲思：
指心理活动的效率、对现实的检验以及道德判断的一种退化，这种退化来自群体内压力。

预防措施：
+ 群体领导应该明确鼓励不同的意见和批评-包括对他们自身观点的批评。
+ 群体领导应该避免在一开始就表明自己的个人偏好。
+ 与其他群体或领导人，一起考虑同一个问题。
+ 群体成员应该与受信赖的同事定期对群体进行审议，并且向群体报告讨论的内容。
+ 群体应该要求群体外的专家或有资格的同事参加会议，并且鼓励他们挑战群体的一致意见。
+ 正式任命某位群体成员担任批评者的角色。

** 群体决策与判断
+ 很多个体水平的直觉和偏差在群体中发挥了同样的效力。
+ 群体讨论通常会加强已有倾向。
+ 群体通常比一般的个体表现好一些，尤其在一名指定的领导者鼓励全体成员发表见解的情况下。
+ 群体中最好的成员通常比群体表现更好。
+ 几个人独自使用头脑风暴比群体会议更为有效。

*** 群体误差和偏差
+ 基本归因误差和群体归因误差有一个共同的基础，那就是我们倾向于忽略行为的外部决定因素，并且想当然的认为行为和一些内在态度之间存在关联。
+ 群体也认为他们自己的成员比其他群体的成员更具有多样性。
+ 外群体同质性偏差的一个重要结果是加深了刻板印象。

*** 群体极化
群体讨论容易增强群体成员达成一致的倾向。

*** 人多智慧多吗
群体比其水平居中的成员做出的判断更为准确，
但群体中最好的成员经常胜过群体整体。

群体讨论的优越性在于汇集的功能，而不是实质上的群体互动。

* 常见陷阱
** 过度自信
几条应对错误校准的策略：
+ 当判断难于做出或极端自信的时候过度自信最强。在这样的情况下，谨慎前行非常必要。
+ 你可能会希望“重新校准”你非常自信的判断以及其他人的判断。
+ 同样，你可能会希望将具有“百分之百信心”的判断自动转变为较低程度的信心。
+ 如果你对某个答案感到极度自信，思考一下另外一个答案可能正确的原因。

*** 准确度和信心之间的关系
+ 当准确度接近机遇水平时过度自信达到最大。
+ 当准确度从50%增加到80%时，过度自信会随之减少;当准确度超过80%时人们会变得不自信。
+ 准确度与智商水平的分离与决策者的智商水平无关。

*** 极度自信
希望表现出色的动机越强烈，过度自信也会随之增长。

*** 校准
校准是指信心与准确度的匹配程度。在给定的信心水平上，
并且当所有准确判断的比例与判断正确的期望概率相一致时，
决策者就获得了最佳的校准。

** 自我实现的预言
+ 关注动机因素。
+ 采用鼓励证伪性回答的方式来组织问题。
+ 通过思考自己的判断在哪些情况下可能是错误的，决策者能够降低过度自信并提高他们的决策质量。

** 行为陷阱
行为陷阱是指这样一种情境：
个人或者群体从事一项很有前景的工作，最后却变得不尽人意并且难以脱身。

当我们避免可能有利的行为时反陷阱就发生了，
而当我们进行可能有害的行为时则出现陷阱。

*** 延期陷阱
任何短期后果和长期后果的冲突都可能是一个延期陷阱。

*** 无知陷阱
*** 投入陷阱
沉没成本效应。

*** 恶化陷阱
也叫可变强化陷阱：
出现在当原先高回报所谓行为逐渐变得不那么有收益或者更具有惩罚性时。

*** 集体陷阱
囚徒困境，公共资源。

*** 深陷泥潭
诱捕：
一个决策过程，此过程中人们持续提高对已被证明是事物的先前选择行为的忠诚度，
目的是使他们以前的投入显得合情合理。

诱捕发生的情境：
+ 在被动地维持现状的情境中比在主动选择继续与否的情况下更加有诱捕倾向。
+ 诱捕在竞争的社会条件下比非竞争条件下激烈，这一点至少对男性而言是正确的。
+ 诱捕不仅发生在个体中，而且在群体中也会出现，尽管这可能仅对女性成立。

*** 胜利解脱
+ 在做出一个承诺之前把结束的成本明确化。
+ 让不同的人进行最初的和后续的决策。

*** 当陷阱是合意时
+ 回避有关诱捕成本的信息。
+ 尽量不做出限定或评估继续这样做将花费的成本。
+ 做出一个公开的、坚持下去的承诺。
+ 与那些有相同目标的人竞赛。
