* 语言的功用
** 语言和生存
语言可以用来叙述语言，在这一点上，
人类的发声机制与禽兽的叫喊有着本质的区别。

文化和智识上的合作，是人类生活的一个重大原则。

** 符号
象征化过程固然人类作出了许多不合理的行为，
却也产生了语言，并使没有语言就不能实现的种种人类的成就得以实现。

符号并不就是其所代表的事物;地图并不就是其所代表的地区;言辞并不就是事实。

我们把这个通过言辞学到的世界叫做言辞世界，把我们直接知道的或是能由个人经验而直接知道的世界叫做外向世界。

** 报告用的语言
从交换知识或信息的角度来讲，我们最基本的象征行为就是把我们所看到的、听到的和感觉到的事情报告给别人。

一般报告都会遵守下面两条规则：
+ 他们是可以证实的。
+ 他们会尽可能避免作出推论和判断。

判断下的太早，往往会使我们看不清楚近在眼前的事物。

我们只要能够领悟到某些字词或某些事实能够引起何种有利或不利的感觉，
那么，就实用目的而言，我们就能达到足够公正的地步。

注意到偏倚技术的读者是不会那么容易受人愚弄的。
他知道得很清楚，除此之外，另外可能还有其他有关的事实，
故意没有给提起。

每个人的经验都先由他按照自己的利益和背景选择节略一番，因此我们大家所得到的经验一开始就是偏倚的。

既然我们不能不从自己的观点出发来看这个世界，我们就要明白自己所看到的是多么有限。
就像一位哲人说的，发现自己的偏见是智慧的开端，摆脱自己的偏见是自由的源泉。
我们若是带着偏见就无法做到公正，进而也就无法提供一幅恰切的地图。

** 前后文
编一部字典并不是发表许多权威性的理论，说明什么是什么字的”真正意思“，
而是尽可能地将不同的字在过去作家的眼光中代表什么意思记载下来。

外向意义-本义（那个字代表的含义）;内向意义-转义或含义。

倘若一句话有外向意义，争论可以有结束，双方也可达成一致看法;
倘若一句话只有内向意义而没有外向意义，我们就可能而且常常会争论不休。

解释字义必须以整个前后文为基础。我们对一个字在事前所能知道的，只是它差不多的意义。
那个字说出口后，我们就能根据它言辞和具体的前后文去解释它的意思，然后载按照我们的解释去采取行动。

我们必须将没有一个字能在两次不同的用法中有同样的意义这条原则记牢，
养成自动考察前后文的习惯，这样才能更好地去理解别人所说的话。

世界上没有一个字只有一个正确的意义，可以一旦用到一种类似的情形上去，
它却真的可以有一种”正确的意义“。这些类似的情形构成一个”字义区“，
字典的功用便是他能解释一个字在各种不同字义区里的意义。
我们每次看到或读到一个字，就可以考察这个字的前后文和它所指出的外向事物，
以决定它在字义区里占了哪一点。

** 有助于社会团结的语言

这种将言辞当成是声音、表达情感的姿势运用，叫做前象征用法。

打破沉默本身就是说话的一个重要功用。我们生活在社会上，
绝对不可能一直要等到“有事情讲”方才开口。

正是靠着大家对一套套固定的言辞刺激有了共同的反应,
人类社会才得以维持完整，不致崩溃。

我们之所以会对世界、人类和民主政治抱有许多悲观看法，
至少有一部分原因就是由于我们无意中把象征语言的标准应用到前象征的言辞上去了。

** 语言的双重任务

表情的语言（例如论断、前象征的作用等）则能感动我们，
也就是说，它能打动我们的内心。感动人的语言有一种如同力量一般的性质。

说话中能感动人的成分：
+ 语调、强弱、声调。
+ 节奏。
+ 感情气氛。

一个字的说明性含义，就是指它经过大家公认并能用别的言辞表达出来的“客观”意义。
一个字的情感性含义是指它在观众心里所唤起的各种感情气氛。

我们要想增进自身理解语言与应用语言的能力，就不能转靠加强我们对语言的说明性含义的认识，而是还得依靠社会经验，
在不同的情形里与不同的人打交道和阅读文学作品等方法，使自己对语言的情感性成分能有更加深切的了解。

** 控制社会的语言

所谓“号令”，“恳求”，”要求“，“命令”，都是我们使用言辞促成事情的最简单办法。

我们用言辞来控制，指导并影响别人未来行动的努力，可以称为语言的指示性用法。

指示性语言依靠情感作用，但是每一个用指示性语言作出或明或暗允诺的人，都有道义上的责任，
必须尽力确保其有足够的把握-世界上不存在百分之百的把握-以免在他人那里引起无法实现的期望。

指示和幻灭：
+ 任何指示都不能使将来完全按照我们心里所想的样子出现。
+ 指示性语言和说明性语言往往比较相似，我们应该能将它们区分开。
+ 我们有时太富于幻想，将指示里并没有的意义看成是它真有的。

** 传达感情的语言

科学使我们能够合作，文艺则能扩展我们的同情心，使我们愿意合作。

隐喻，直喻，忘隐喻，典故，幽默。

每一种文化里的青年人都得研究他们自己的文学和历史，
原因之一就是，只有这样他们才能去理解并参与自己群体内思想和感情的交流。

** 艺术和激荡的情绪

作家借助语言将其经验和态度整理出来，从而在读者心中产生作用，
使读者也能把个人经验和态度略事整顿。经过这番整顿，
读者的内心也就可以变得略微整齐些。这就是艺术的目的。

* 语言和思想
** 我们是怎样得到知识的
抽象化阶梯：
我们经验里的物体并不是东西本身，而是我们的神经系统与神经系统以外的东西互相起的作用。

定义对于一般事物一点也不能说明什么东西。它们只能描写大家的言语习惯，
也就是说，它们只能告诉我们在什么情况下大家会发出什么声音，我们应该把定义视为关于语言的陈述。

沿着抽象阶梯下降落到抽象阶层的习惯，那种在语言里转来转去找不到方向的可能也会减少许多，
而且还会有“脚踏实地”“言之有物”的倾向。

唯一的办法就是越少用定义越好，随时随地指着外向阶层-也就是说，无论写作还是说话，
我们都应引用具体实例来证明自己讲的是什么。

现在流行一种趋势，每逢说道“不过是一抽象名词而已”，总是对抽象名词报持一种轻视态度，
这种态度固然可以理解，却也是一种不幸的现象。
沿着抽象阶梯一层一层地上升显然是人类特有的一种能力，没有这种能力，我们也就不能获得哲学和科学上的见解。

检验抽象名词的标准并不是它们的抽象阶层“高”或“低”，而是能不能从它们推引到较低些的阶层。
只要他们说的话能够有系统地、切实地推引到较低的抽象阶层，他们就并不是“空口说白话”，而是言之有理。

显然，有趣的谈话和写作，以及清晰的思想和随之而来的和谐心境，
都需要高级抽象阶层与低级抽象阶层、语言与现实不停地互相发挥作用。

** 捕风捉影
文明愈加进步，我们就愈加能够感受到我们的神经系统自动地略去了当前事物的特征。
倘若我们不知道有些特性已被略去，或者感觉不到抽象化过程，我们便会一看见某种
事物便信以为真，从而使看见和相信你成为一个过程。

许多谣言之所以愈传愈夸张，就是因为有些人忍不住要向更高的抽象阶层上走，
从报告进展到推论，从推论进展到判断，然后再把不同的阶层混杂起来。

一个方法是要深刻认识到，言辞与他们所代表的事物之间并没有“必然联系“。
另一个办法就是注意到抽象化过程，由此亦可减少或摆脱对人对事的的偏见。

** 分类
我们把事物叫做什么名字、在哪一点或哪条线是上将两种不同的东西分开，
和会根据我们的利益和分类目的而定。

忽略了在分类过程中被忽略的特征，也就等于忽略了差异。

总之，哪些分类法能够产生社会需要的结果，社会就会把那些分类法视为真理。
但是，科学家所想要的结果就是只要我们的分类法产生的结果能够预测就行。

** 二元价值观点与多元价值观点
二元价值观点只能产生争斗精神，而无法提升我们准确评价世界的能力。
除非我们是以争斗为目的，否则在这种看法的领导下，我们最后得到的结果总是会与原来的目的相反。

区分越精细，我们能够想到的行动方式就会越多。这也就是说，
对于人生中许多负责的情形，我们也就更有能力做出合适的反应。

一种民主政体越是发达，它的价值观点越是富于伸缩性，也就是越能够调剂民众间的相互冲突的欲望。

在当今的文明社会中，二元价值观点可能仍是一种启动工具，因为它有传达感情的力量，能够引起人们的兴趣;
然而，把我们载到目的地的转向工具确是多元价值或无穷多元价值观点。

要想从谈话中得到最大的好处，有一个重要的方法就是有系统地应用多元价值观点。

定义一点也不能解释什么，它们只能描写别人的语言习惯。

** 一团遭
内向观点-也就是说，只根据言辞而不是根据言辞所代表的事实去采取行动。
包含下面这些比较具体的错误：不注意前后文，自动反应倾向，把不同抽象阶层混为一谈;
只注意相同的地方，不注意不同的地方；满足于用定义解释言辞。

在评价过程中，情愿以言辞为根据而不情愿以事实为根据是一个严重的病症。

** 老鼠和人
所有的制度都有一个特别之处，那就是，你只要对自己的制度习以为常，
最后就会觉得它是唯一正确而恰当的行事方式。

每个人都倾向于保护自己的制度，使它们不致受到挑战和攻击。
这一事实是社会之所以能够稳固存在的基础。

我们必须把社会问题当作制度适应问题看待，这样一来，
许多激烈争辩的社会问题中的种种疑难就会慢慢自动变得外向的，我们便会不再追问某个改变制度的建议是对的还是错的，
是进步的还是反动的;而是改问以下问题：结果如何？谁能得到利益？能得到多少？谁会吃亏？吃亏到什么程度？
在这个建议里有哪几点可以保证将来没有坏处？一般大众对这个法案是否已经做好准备？
对物价、劳工供应、公共卫生或其他问题可能会有什么影响？谁这样主张的？
根据谁的研究心得、那一门专门知识？

我们把平常用来观察社会问题的态度往往包括习俗的道德观点，所以我们总是会批评这个批评那个，
或者互相批评。这样一来，我们便完全忽略了“测绘”社会问题的基本条件，
也就是说，我们原本应该先把那些组成一个社会和造成它的社会问题的固定行为方式描写出来。

** 走向内心和外界的秩序
外向观点的规则：
+ 一张地图并不是它所代表的地域，言辞并不就是事物。
+ 言辞的意义并不在言辞中，而在我们的脑海中。
+ 前后文决定意义。
+ 留心是字，因为它可能代表一种错误的评价法。
+ 不要没有造桥就想从上面走过去。认清指示和说明之间的差别。
+ 认清真字至少有四种不同意义。
+ 当你想要以火攻火的时候，记住消防员平常总是用水的。
+ 二元价值观点是启动用的机器，不是驾驶用的机器。
+ 小心定义，它是用言辞解释言辞。如果可能，思考时用实例而不是用定义。
+ 用指数和日期来提醒自己，没有两个字能有两次意思完全相同。

相反，一个思想成熟的人知道言辞从来不会把所有事物描述清楚，故也能适应不测。

一个有智慧的人并不对所有事情都完全了解。可是他也没有感到不安全的情形，
因为人生中唯一可能有的安全，就是来自内心的主动安全：
这种安全的泉源便是一种无穷多元价值观点得来的伸展自如、灵活无比的心境。

这种地图与地区不相符合的情形，不但威胁到我们的自我评价，而且威胁到我们对别人和外界事物的评价。
事实上，我们估量别人和外界事物时的智慧，多半都要视我们自我评价时智慧的高低而定。

另一种可以增加对自己的外向觉悟的办法，是将制度化的态度和外向得来的态度分开。

这种制度化的态度包含了许多普遍的、错误的评价法，
这是因为每一种制度化的态度都会涉及到一个处于较高抽象阶层的、概括的观念。

除非一个人知道要在经验里寻找什么，否则他的经验对他毫无用处。
除非是有人把我们的眼睛打开，要不我们大家都只会闭着眼睛在世界上乱转圈子。
